### ISSUE TITLE
[FeatureRequest] Different icons for bookmarks

### ISSUE THREAD

**Issue by minj** [IgnorantGuru/spacefm#157]
You can change the bookmark icon but all bookmarks always have the same icon. Some customisation would be nice :]

**Comment by IgnorantGuru** [comment]
This has been implemented in the under-development book branch - will be announced for testing shortly.  In the the new version, you can select a custom bookmark icon, a custom bookmark submenu icon, and also set individual icons for each bookmark.

**Comment by Xylemon** [comment]
This is great to hear!

**Comment by IgnorantGuru** [comment]
Please see #492 to help test new features.

**Comment by tschallacka** [comment]
Has this request been implemented yet?

**Comment by ncmprhnsbl** [comment]
> Has this request been implemented yet?

yes
