### ISSUE TITLE
mount point not detected on btrfs device

### ISSUE THREAD

**Issue by IgnorantGuru** [IgnorantGuru/spacefm#165]
Received [elsewhere](https://bbs.archlinux.org/viewtopic.php?pid=1168622#p1168622):

> When I click on the list of devices on the left, the devices mount. It then lists the mount point after the device, but one of my partitions doesn't. when I click on it again, instead of taking me to the mount point, it gives me an error that it's already mounted. I can access it through the normal mount point, so it <i>is</i> mounting correctly.

**Comment by Vladimir-csp** [comment]
```
spacefm 1.0.6
GTK3 UDEV INOTIFY DESKTOP SNOTIFY
```
I currently have this problem. The volume has default subvolume `/@` and is mounted, but not detected as mounted by SpaceFM
