### ISSUE TITLE
Option to use "~/.gtk-bookmarks"

### ISSUE THREAD

**Issue by jpfleury** [IgnorantGuru/spacefm#21]
*Note: this is a copy of the [ticket 9 on the SourceForge tracker](https://sourceforge.net/p/spacefm/tickets/9/).*

What about an option to use bookmarks defined in `~/.gtk-bookmarks`? This file is already used by Nautilus, Thunar...

Personally, I use Thunar a lot, and having a way to share bookmarks between the 2 file managers would be useful.

**Comment by IgnorantGuru** [comment]
Please see #492 for related Bookmarks changes in the next version, and also the new [Bookmarks](http://ignorantguru.github.io/spacefm/spacefm-manual-next-en.html#gui-book) section of the manual, which describes SpaceFM new options and behavior wrt GTK's bookmarks.

**Comment by root2185** [comment]
When you select an icon it opens a "File Picker Dialog" that use gtk bookmarks from `~/.config/gtk-3.0/bookmarks`.
Is there a way to import them? And where are saved `spacefm` bookmarks?
