### ISSUE TITLE
Add tooltips on toolbox and sidebar

### ISSUE THREAD

**Issue by jpfleury** [IgnorantGuru/spacefm#22]
*Note: this is a copy of the [ticket 10 on the SourceForge tracker](https://sourceforge.net/p/spacefm/tickets/10/).*

Icons in the toolbox and the sidebar don't have any tooltips when we put the cursor hover. I think it would be a good idea to add this usual feature.

For example, putting the cursor hover the Refresh icon could display a tooltip *Refresh the current folder*.

**Comment by IgnorantGuru** [comment]
Tooltips are now shown on the toolbars in the upcoming version.  Please see #519 for testing.
