### ISSUE TITLE
Separator in bookmarks panel

### ISSUE THREAD

**Issue by jpfleury** [IgnorantGuru/spacefm#26]
*Note: this is a copy of the [ticket 49 on the SourceForge tracker](https://sourceforge.net/p/spacefm/tickets/49/) originally created by Omega Weapon.*

Please could you implement separators in the bookmarks panel - i.e. a line visually separating groups of bookmarks, that can be added and removed from the panel in the same way that bookmarks can be currently.

I currently do this in a crappy way by bookmarking to meaningless directories like '== Standard =='.

Thanks

**Comment by IgnorantGuru** [comment]
Bookmarks separators (and submenus) have been implemented in the under-development book branch, to be announced for testing shortly.

**Comment by IgnorantGuru** [comment]
Please see #492
