### ISSUE TITLE
No automatic refresh after CIFS file operations

### ISSUE THREAD

**Issue by serge-stroobandt** [IgnorantGuru/spacefm#282]
I have been using SpaceFM 0.8.6 and earlier version now for a while on a Linux Mint Debian Edition (LMDE) system with the XFCE 4.8 desktop. I use it as an excellent replacement for the Thunar file manager.

What I do not like though, is that after file operations (copying, moving, renaming, etc.) I have to manually refresh to see up-to-date folder contents.

Can this refreshing not be automated like in other file managers?

**Comment by IgnorantGuru** [comment]
A change detection blacklist is now an option in the hand branch.  See #478
