### ISSUE TITLE
watch bookmarks for changes

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#303]
This is particularly useful if bookmarks are linked to ~/.gtk-bookmarks.
If something adds/removes/changes a bookmark, SpaceFM does not display the change and overwrites file with old content on exit.
Things like xdg-user-dirs-gtk-update break.

**Comment by Vladimir-csp** [comment]
Any chance this might get some attention for 1.0?

**Comment by IgnorantGuru** [comment]
In the under-development book branch, SpaceFM no longer uses a bookmarks file, nor does it have any relation to gtk bookmarks, except it may import them.  You'll see the details when that's announced shortly.  So watching that file will not be done.
