### ISSUE TITLE
Can not drag and drop a file from spacefm to firefox

### ISSUE THREAD

**Issue by jpfleury** [IgnorantGuru/spacefm#33]
*Note: this is a copy of the [ticket 88006 on the SourceForge tracker](https://sourceforge.net/p/spacefm/tickets/88006/) originally created by Anonymous.*

In nautilus, I can drag a file and drop it into firefox and uploaded it to remote app. (for example : Gmail/ Compose new email). But in spacefm, I can not drag and drop a file to Gamil)

**Comment by OmegaPhil** [comment]
Confirmed that this works for me with Firefox v38.2.1 using Imgur image upload as a test, hasufell and others have already done a lot of testing on this so I think this is no longer a problem.
