### ISSUE TITLE
Right click clears multiple-file selection

### ISSUE THREAD

**Issue by skalteis** [IgnorantGuru/spacefm#353]
Hello,

I am using SpaceFM 0.8.7 on Debian 7.1 and there is a very annoying bug present.

If you select multiple files in a newly started instance of SpaceFM and then right-click on that selection to act on it (e.g. copy - doesn't really matter which action...), as soon as the pop-up menu appears, the selection is cleared and only the entry right under the mouse pointer is selected.
Strangely, after a few tries it starts to work sometimes.
Sadly, this is a real showstopper in what is otherwise the only GUI file manager worth its salt for Linux at the moment. :-)

Thanks for your time & effort!

Simon

**Comment by IgnorantGuru** [comment]
I think I finally found a fix for this - in next branch, due for 1.0.2 release.  To test please see BUILD NEXT instructions in README.

What seemed to be happening here was that the button click was on the file list and the button release was on the menu, similar to #521.
