### ISSUE TITLE
mtp mount not detected

### ISSUE THREAD

**Issue by mullenkamp** [IgnorantGuru/spacefm#362]
I know that another (closed) thread has a similar question, but nevertheless it still seems to be a problem. The original explanation was that mtpfs was bad.

I am running Lubuntu 13.04.
No matter what type of mtp mount program I have used (i.e. gmtp, go-mtpfs, gvfs-mtp, etc), Spcefm would not recognize the mtp mount. After getting frustrated enough, I decided to open up PCmanfm. To my surprise, the mtp mount was there and I could access my device.

Any idea why PCmanfm recognizes the mtp mount and Spacefm does not?

Thanks.

**Comment by mandeeps708** [comment]
Installing `jmtpfs` didn't work for me.

**Comment by IgnorantGuru** [comment]
@mandeeps708 Modern versions of SpaceFM (1.0.0 and later) use handlers for protocols, so you can see the handler in Devices|Settings|Protocol Handlers, then click on "mtp".  You can also add your own handler to run whatever you want to use to mount mtp.

The provided mtp handler (by @vladimir-csp) requires one of these to be installed: jmtpfs || simple-mtpfs || mtpfs || go-mtpfs

If that's not working, you can run the first instance of SpaceFM in a terminal to see what handler is being used and any errors produced.  If you think there's a bug, please open a new issue and include the output of 'spacefm --version'.
