### ISSUE TITLE
panel1 tree: add navigation keybinds to improve accessibility / usability

### ISSUE THREAD

**Issue by stewie** [IgnorantGuru/spacefm#370]
when panel1 has focus:

down arrow: move focus to next (sibling) node
up arrow: move focus to previous (sibling) node, else move focus to parent node
right arrow: if subdirs exist, expand branch and focus first child node
left arrow: walk "up", focus parent node

Without these keybinds, browsing requires LOTS of mouse clicks

**Comment by IgnorantGuru** [comment]
This may already now be working as described, with changes in #541 #542 and #575 ?  It already had the keybinds in there, I think the issue was the loss of focus due to the directory being entered as you move.  Now you press enter.
