### ISSUE TITLE
Extracting in terminal

### ISSUE THREAD

**Issue by ghost** [IgnorantGuru/spacefm#395]
Archives with formats rar, zip and 7z are extracted in terminal, with only reason (if my understanding is correct) to give user option to type password if archive file is password protected.

My suggestion is to add some dialog where user could type those passwords, and not extract files in terminal.

Is this good idea?

**Comment by IgnorantGuru** [comment]
This is now possible in the hand branch  See #478   SpaceFM doesn't show password prompts, runs in terminal, but the user can now adjust archive commands to show a popup, etc.
