### ISSUE TITLE
[feature request] translate URL into already mounted path

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#398]
To increase transparency of walking through URL links I suggest testing if given URL is already mounted and translate it into mounted path.
For example: 
If we open URL smb://server/share/somedir/someotherdir in spacefm, it should check if smb://server/share[/somedir][/someotherdir] (from root to last) is already mounted. If it is, translate smb://server/share/somedir/ into mounted path, i.e. /media/smb-server-share/somedir/someotherdir and open it.
If link URL points to file, then it should open directory and select file.

**Comment by IgnorantGuru** [comment]
This should be complete in hand #478

**Comment by Vladimir-csp** [comment]
Mounted ssh://user@server:12345/home/user
Then tried to enter ssh://user@server:12345/home/user/subdir. SpaceFM initiated second mount.

**Comment by IgnorantGuru** [comment]
While perhaps not ideal, that behavior is expected at this point.  I'm mainly concerned that two identical URLs don't mount twice in most cases.

There isn't the logic in there to find the subdir added to an already mounted path.  In some cases the protocol handler may want to do this when a mount is requested, opening an existing mount point instead.  For example the Mount ISO file handler does this with ISO files.
