### ISSUE TITLE
Paint root window with selected color when there is no wallpaper

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#404]
When desktop wallpaper is disabled or not does not exist, and simple color is used, real root window may still contain bitmap that was set before spacefm launch, or with previous wallpaper.
Apps that use fake transparency (i.e. conky, some panels) grab that bitmap and ignore solid spacefm background that overlays root window. This produces inconsistency.
SpaceFM should paint root window with selected color if background image is disabled

**Comment by IgnorantGuru** [comment]
Teklad's fix for this has been merged into next and alpha, due for 1.0.6 release.  Works for me.
