### ISSUE TITLE
REQUEST - Desktop - Wallpaper - Please Make An Option To Disable It?

### ISSUE THREAD

**Issue by ghost** [IgnorantGuru/spacefm#448]
Hi IgnorantGuru,

For those that have no need for Desktop management with the Desktop section options, can you please make an option in a future version of SpaceFM to disable this? So that under the Preferences - Desktop this will be removed for those that want to strip down SpaceFM further...

--disable-desktop

Thank you for your consideration IgnorantGuru, I hope you'll please implement this.

By the way keep up the great work on this wonderful app. :)

**Comment by IgnorantGuru** [comment]
https://github.com/IgnorantGuru/spacefm/commit/db0440536997e378fc0941f0bbc487b8eb1dada8 hides the Desktop tab in Preferences when SpaceFM is built with configure option --disable-desktop-integration.  This also corrects a problem where runtime option --show-pref=N would not show the Advanced tab.

This is in the next branch, due in 0.9.5 release.
