### ISSUE TITLE
Support new mime specification

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#450]
The document is here: http://standards.freedesktop.org/mime-apps-spec/mime-apps-spec-latest.html
It seems that KDE already started some work on implementation http://web.archiveorange.com/archive/v/bZBuSmXLkzbCWLZ8hAOG
Definitely a thing to be kept in mind. 

Main changes:
[Default Applications] section is legalized and takes precedence.
User configuration moved from $XDG_DATA_HOME to $XDG_CONFIG_HOME, but old location is still valid for compatibility.
Hierarchy now contains general and prefixed lists for DE-specific overrides.

**Comment by lierdakil** [comment]
Well, it's been a year, and 'Default Apps' is used by pretty much everything and its dog now. This currently creates  some problems for me, as I have to manually maintain both `Default Apps' and 'Added Associations' to keep behavior consistent between spacefm and xdg-open (which is used basically by everything else). Any chance this is getting implemented anytime soon? If not, could someone suggest a workaround?

**Comment by IgnorantGuru** [comment]
Until this is updated, which I'd like to do soon, also note that you can use the new File Handlers to bypass the MIME system when opening files within SpaceFM.  Right-click on a file and select Open|Handlers.

**Comment by IgnorantGuru** [comment]
@Vladimir-csp 
> What algorithm SpaceFM uses to parse .desktop files for associated apps?

You can see these functions in [mime-action.c](https://github.com/IgnorantGuru/spacefm/blob/next/src/mime-type/mime-action.c).  I rewrote some of that 2 years ago when it brought it up to what was then the pretend-spec from these idiots.

Any sign other file managers are actually using the new spec for real, or are they still merely using the broken/hybrid implementation of Added Associations?  eg can I use Thunar as an example of desired behavior, or is it still half-broken?

The other issue here is that Freedesktop gives NO thought to backwards compatibility everytime they randomly change their bloated specs (that are hell to implement from a performance standpoint - these people have no clue what they're doing.)  As SpaceFM is still used on older systems, updating its handling of this without breaking it for older systems may require additional care.

**Comment by IgnorantGuru** [comment]
And in case you just think it's me saying that, look at the original comments by PCMan in the code, eg:
> * This API is very time consuming, but unfortunately, due to the damn poor design of
> * Freedesktop.org spec, all the insane checks here are necessary. Sigh... :-(

And now they've made it worse.  But if it's not too ridiculous I'd like to bring SpaceFM to reasonable compliance, or otherwise drop MIME entirely.  Anyway if you've been following the latest I'd like a summary of where things stand wrt to the viability of the spec and whether it's actually being implemented by other file managers.

**Comment by IgnorantGuru** [comment]
I looked over that spec again.  As I said above I don't intend to fully implement that spec, as it's too wasteful, both in terms of performance and in terms of the amount of new code that would need to be written to fully comply with it.  Performance can take a big hit with specs written like that.  Also, the people  maintaining these specs are too unreliable and are moving to ever greater levels of complexity, which is not a trend SpaceFM will be following.  I'm not investing a lot of time in their unpredictable changes, especially with the way they've been changing and (not) maintaining things.  I also doubt that other FMs are fully in compliance - from what I've seen of MIME handling, it's a mess, in large part thanks to Freedesktop.

But in the interests of making SpaceFM work reasonably with other FMs, here is what I'm thinking in general:

* If a user makes an app the default in SpaceFM, it will add it/move it to the first position in Default Applications, do the same to Added Applications, and remove it from Removed Applications if needed, leaving the other entries (and their order) in those lists unchanged (so as not to break the use of apps that may be more fully spec compliant).  This portion at least sounds spec compliant, if not in the true spirit of the spec.

* If a user removes an associated app in SpaceFM, it will remove it from Default and Added Associations, and add it to Removed Associations.  Again, this portion sounds spec compliant.

* The above means that all ***changes*** SpaceFM makes to mimeapps.list will be fully spec compliant (it won't break other apps that are fully compliant).

* However, in *reading* mimeapps.list, both the local as well as system copies, SpaceFM will probably ditch strict compliance, and just do a best guess algorithm to determine and list default and associated apps (similar to how it works now, but merging Default Applications on top of Added Applications).  This means that SpaceFM should be correct 99% of the time when determining a default app, but in unusual cases it may select a different one than a fully compliant app will.  This will only effect apps for which the user has not set any overrides in any app.  In those cases, the user can set a preferred default app in SpaceFM (or in another app) which will update mimeapps.list and thus sync all apps for that MIME Type.

* One exception I see may be that SpaceFM won't honor system files dictating what associations cannot be removed by the user, which I think is a stupid rule and SpaceFM won't obey it.

Comments?

**Comment by Vladimir-csp** [comment]
I haven't seen any active discussion of mime spec on XDG mailing list recently. 
Your plan sounds good. But do not rush it yet if you have other important tasks at hand.
I will review recent movements regarding the spec in the next couple of days and see if there is something useful.

**Comment by IgnorantGuru** [comment]
I have pushed a temporary 'mime' branch that implements the above changes I described.  The way it looks for default and associated applications is much like before except it now sees "Default Applications" in mimeapps.list files.

That branch can be tested using the BUILD NEXT instructions in README, substituting 'mime' for 'next' in those commands.

Please test to see if this responds as expected in various situations.  The only file updated is mimeapps.list.  The older defaults.list is read if needed to find a default app to open a file, but is not read to find all associated apps, and it is not updated (as before).  Use of that file is deprecated.

**Comment by Vladimir-csp** [comment]
I've tested PCManfm-QT and Thunar, they seem to follow latest spec, preferring and writing to $XDG_CONFIG_HOME/mimeapps.list, getting default from [Default applications], ignoring order of [Added associations] when deciding on default.

**Comment by Vladimir-csp** [comment]
SpaceFM mime branch prefers $XDG_DATA_HOME, but otherwise works fine on first glance.

**Comment by IgnorantGuru** [comment]
$XDG_DATA_HOME defaults to ~/.local/share
$XDG_CONFIG_HOME defaults to ~/.config

So you're saying they are reading and writing mimeapps.list as *~/.config/mimeapps.list* instead of *~/.local/share/applications/mimeapps.list* ??

I see that in the spec, but I find it hard to believe - seems like a bizarre place to put it.  So SpaceFM should first look for *~/.config/mimeapps.list*, then if that's not found, for *~/.local/share/applications/mimeapps.list* ?  (allowing for $XDG's real values, which I think is handled by glib) 

And it should update both all the time or just the one it reads?

**Comment by IgnorantGuru** [comment]
d130c25 looks in both $XDG_CONFIG_HOME/mimeapps.list and $XDG_DATA_HOME/applications/mimeapps.list.  When updating it, it will only update the one it first finds (should it update both for backwards compatibility?).

I assume mimeinfo.cache is still in $XDG_DATA_HOME/applications/ - it only looks there for it.

Also, what do you suggest for upgrades?  If $XDG_CONFIG_HOME/mimeapps.list doesn't exist, copy $XDG_DATA_HOME/applications/mimeapps.list there?

I left debugging enabled in this branch, so if you run spacefm in a terminal it will show you where it's looking and the order.  Thanks for testing - take your time.  I'm not in a hurry with this but when it looks reasonable and we've addressed the above questions, we'll push it to next for more testing.

**Comment by Vladimir-csp** [comment]
PCManFM and Thunar write to $XDG_CONFIG_HOME/mimeapps.list, creating it if needed.
I see no problems on update, since $XDG_DATA_HOME/applications/mimeapps.list remains further in precedence.

I entirely missed the moment when XDG changed config order introducing $XDG_CONFIG_HOME elements.
Anyway, here is a (bit outdated) thread about the direction of algorithm and performance: http://lists.freedesktop.org/archives/xdg/2014-April/013287.html 
Another sidenote that may be useful: https://bugs.freedesktop.org/show_bug.cgi?id=89877

I also saw in some threads that handling of the spec is implemented in glib, so is there really a need for your own implementation? Maybe just use glib for that, it is in dependencies anyway. I suspect that both PCManFM and Thunar do their mime work via glib. Or am I missing something here?

**Comment by Vladimir-csp** [comment]
...or I didn't miss the change, just forgot about it. Damn.
 http://lists.freedesktop.org/archives/xdg/2014-April/013286.html

**Comment by IgnorantGuru** [comment]
It wouldn't be glib afaik - nothing mime related in there.  Except it can give me the user's .config dir, for example, so I don't have to interpret $XDG vars, etc. directly.  Perhaps they meant gvfs, but that's a whole other foundation.

This approach works for me for now.  If anyone has specific functional problems in actual use, I'll consider addressing them on a per-issue basis, which is how Freedesktop tends to be in SpaceFM - it's not fully compliant but just gets along reasonably well with it.

**Comment by IgnorantGuru** [comment]
mime branch has been merged into next.  The debugging info was removed, but if you'd like to test with it, just install the d130c25 branch -  none of the logic changed.  Also, user's manual has been updated.

**Comment by Vladimir-csp** [comment]
I think it should also create mimeapps.list in $XDG_CONFIG_HOME if it does not exist.

**Comment by IgnorantGuru** [comment]
> I think it should also create mimeapps.list in $XDG_CONFIG_HOME if it does not exist.

This is why I asked about upgrade behavior, and if $XDG_DATA_HOME/applications/mimeapps.list should be copied to $XDG_CONFIG_HOME/mimeapps.list.

Currently, if $XDG_DATA_HOME/applications/mimeapps.list exists, it will update that.  If $XDG_CONFIG_HOME/mimeapps.list exists, it will update that.  If neither exists, it will create $XDG_CONFIG_HOME/mimeapps.list.  So it already does create it.

The problem I see with merely creating a blank $XDG_CONFIG_HOME/mimeapps.list is that if you downgrade SpaceFM, or use an older file manager, it won't see your recent associations - it will only read $XDG_DATA_HOME/applications/mimeapps.list.

Ofc this is the kind of breakage they create by moving files for no good reason.

So what specifically are you proposing as SpaceFM's new behavior?  Should it never update $XDG_DATA_HOME/applications/mimeapps.list and just write new changes to $XDG_DATA_HOME/applications/mimeapps.list ?

**Comment by Vladimir-csp** [comment]
> PCManFM and Thunar write to $XDG_CONFIG_HOME/mimeapps.list, creating it if needed.
I see no problems on update, since $XDG_DATA_HOME/applications/mimeapps.list remains further in precedence.

That was my answer on upgrade behavior question, I meant that data in $XDG_DATA_HOME/applications/mimeapps.list would still be accessible through hierarchy and creating $XDG_CONFIG_HOME/mimeapps.list and writing new data into it would cause no problems.
I didn't know that 'downgrade question' was also included :)

But anyway, IMHO this change should be made, with appropriate notes in manual and changelog.
Downgrade is not an everyday issue.

**Comment by IgnorantGuru** [comment]
Okay ae6b59e will only create/update $XDG_CONFIG_HOME/mimeapps.list

With this change, those upgrading may lose removed associations that were previously set in the old mimeapps.list.  SpaceFM reads both locations when determining default apps, but only reads $XDG_CONFIG_HOME/mimeapps.list when determining what associations have been removed.

Also, SpaceFM users can no longer effectively use $XDG_DATA_HOME/applications/mimeapps.list  since it will not be updated.

**Comment by IgnorantGuru** [comment]
@Vladimir-csp Thanks again for your extensive research and testing on this!

**Comment by Vladimir-csp** [comment]
No problem, thank you for the great FM!
