### ISSUE TITLE
0.9.4 - Unmount & Sync - Stuck On 50% & NTFS Issues...

### ISSUE THREAD

**Issue by ghost** [IgnorantGuru/spacefm#451]
Specs;
SpaceFM 0.9.4
udevil-0.4.3
(2) WD My Passport Ultra 2TB USB 3.0
(1) usb logitech keyboard & (1) usb logitech mouse

I only have four 3.0 usb ports on my laptop and today I was using all of them with both WD drives plugged in and my usb logitech keyboard & mouse in the other two ports, and while running; dd if=/dev/zero of=/dev/sdb bs=1M to clear one of the WD drives, I noticed that with any other usb device I plugged in and tried to unmount and sync, the sync would get stuck on 50% and never complete, and I've never had this happen till now, so I'm wondering if doing dd on one usb device while trying to unmount and sync another usb device is giving spacefm/udevil problems?

I've also always had typically two partitions on my USB drives ext4 & ntfs. I can't really tell you the amount of times this has happended, but on occassion I'm seeing SpaceFM/udevil not unmounting properly because when I try to then use a usb device in Windows with the ntfs partition, I've had happen a few times, Windows will complain the device needs to be checked.

I know this is a mount issue out of spacefm/udevil because I've never had Windows complain to check the disk when I mount/unmount manually at the terminal.

**Comment by IgnorantGuru** [comment]
Unmount runs umount, which itself performs a syncfs.  This is like a sync, but just applies to the filesystem being unmounted.  A "general sync" means the 'sync' command is run, which syncs all filesystems.

In general, using Unmount in SpaceFM should be sufficient.

Note that some disks have large hardware caches, which may not be flushed immediately, even after a sync completes.  This is not under the OS control.  This is an area where Linux does not have a uniform solution, particularly for non-root users who can't send commands to the disk hardware telling it to flush.

What this means in practice is that with some USB sticks and drives, you may see lights flashing even after the sync, and it is vital to wait a few seconds before removing it.

If that solution is not sufficient, you can research a method for forcing your drive to flush it's hardware cache, and you can add a custom command to SpaceFM's Devices menu containing these commands.
