### ISSUE TITLE
EXEC(/usr/share/applications/.desktop) messages in console

### ISSUE THREAD

**Issue by moulei** [IgnorantGuru/spacefm#460]
I just noticed that when you run spacefm 0.9.4 from the command line, and any file 
that is associated to an application, mime, when you click in spacefm on a file, 
spacefm will output to the terminal these types of messages;

EXEC(/usr/share/applications/geany.desktop)=geany %F
EXEC(/usr/share/applications/mpv.desktop)=mpv --really-quiet --force-window -- %F
EXEC(/usr/share/applications/leafpad.desktop)=leafpad %f

I hope this is something you can please silence in SpaceFM it really starts to 
fill the console up with a lot of output fast.

thank you

**Comment by IgnorantGuru** [comment]
Verbose by design, no plans to change this, but others are welcome to add input.

**Comment by moulei** [comment]
Ahh ok, to bad it wasn't just a switch option if you wanted to turn it on as;

spacefm -v

Maybe in the future this can change.

thank you
