### ISSUE TITLE
Installing SpaceFm From **hand** Branch

### ISSUE THREAD

**Issue by r004** [IgnorantGuru/spacefm#461]
hello and tnx for your great FM; Linux and BSD community needs project like this. (Very said about the news).
Anyway; as branch comparison shows; branch `hand` is 206 commit ahead of master branch.
Is that means the most up to date version of SpaceFM is on **hand**?
Is that stable too?

**Comment by IgnorantGuru** [comment]
jfyi, the hand branch was to be the next major version of SpaceFM, and actually was almost complete when development was suspended - just needed some finishing up and testing.  I don't recommend using it, but if someone wants to continue any major development, that would be a promising branch to fork from.  If I ever resume development, I will likely begin by completing that branch - no current plans on that.  OmegaPhil is most knowledgeable on that branch.

The user's manual in that branch explains most of the new functionality, but as I said it is still untested and somewhat incomplete.
