### ISSUE TITLE
Problem mounting removable btrfs and f2fs filesystems

### ISSUE THREAD

**Issue by lockheed** [IgnorantGuru/spacefm#462]
Clicking on devices in SpaceFM mounts USB disks with fat and extX filesystems, but does not work for btrfs and f2fs. In such case, I get:

>Finished with error  ( exit status 5 )
>
>NTFS signature is missing.
>Failed to mount '/dev/sdd1': Invalid argument
The device '/dev/sdd1' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?
NTFS signature is missing.
Failed to mount '/dev/sdd1': Invalid argument
The device '/dev/sdd1' doesn't seem to have a valid NTFS.
Maybe the wrong device is used? Or the whole disk instead of a
partition (e.g. /dev/sda, not /dev/sda1)? Or the other way around?
cases useful info is found in syslog - try
       dmesg | tail or so.

**Comment by IgnorantGuru** [comment]
What mount solution are you using with SpaceFM? (eg udevil, udisks, udisks2)  Running SpaceFM in a terminal and providing the output seen when attempting to mount may be helpful.

**Comment by lockheed** [comment]
I only have pmount installed.

Here's the output:

$ spacefm

TASK_COMMAND(0x18ed000)=/usr/bin/pmount /dev/mmcblk0p1
SPAWN=/bin/bash  /tmp/spacefm-juha-071e5866.tmp/64cff727-tmp.sh  run
    pid = 8893
child finished  pid=8893 exit_status=5
udev changed: /dev/mmcblk0p1

**Comment by IgnorantGuru** [comment]
I'm not sure that pmount supports btrfs at all.  In any event, the error message is coming from pmount.  You can try running the pmount command directly in a terminal to debug it.  Or you can install udevil which should correct the problem.

It could be pmount needs you to specify the filesystem type with -t.  Currently you can't do that via SpaceFM (without writing a script or a custom command just to mount that type).

Closing this as it doesn't appear to be a problem in SpaceFM's behavior but feel free to add any info you discover.

**Comment by lockheed** [comment]
Ok, udavil made it work, but I stumbled onto another problem:
My mount options are:
noexec, nosuid, noatime, flush, compression=lzo+btrfs, autodefrag+btrfs

so if I mount a f2fs partition, the last two should be ignored. However, they are not:
udevil: denied 90: option 'compression=lzo' is not an allowed option

**Comment by IgnorantGuru** [comment]
Are you sure it is btrfs?  Try right-clicking on the device in SpaceFM and select Properties, see how the fstype is listed in USAGE and also under INFO|type:

**Comment by lockheed** [comment]
It is F2FS. That's the whole point so that SpaceFM ignores btrfs flags when mounting it.

**Comment by IgnorantGuru** [comment]
Have you added compression=lzo to any part of /etc/udevil/udevil.conf, such as to default_options?  That may also create this situation.

If not, please post the terminal output of SpaceFM when executing the mount, so I can see the udevil command being issued.

**Comment by lockheed** [comment]
No changes to default udevil.conf

$ spacefm

TASK_COMMAND(0x2752000)=/usr/bin/udevil mount -o 'noexec,nosuid,noatime,compression=lzo,autodefrag' /dev/mmcblk0p1
SPAWN=/bin/bash  /tmp/spacefm-juha-643e8953.tmp/7253f8de-tmp.sh  run
    pid = 24135

TASK_COMMAND(0x2752150)=/usr/bin/udevil mount -o 'noexec,nosuid,noatime,compression=lzo,autodefrag' /dev/mmcblk0p1
SPAWN=/bin/bash  /tmp/spacefm-juha-643e8953.tmp/30fbb331-tmp.sh  run
    pid = 24139
child finished  pid=24135 exit_status=2

**Comment by IgnorantGuru** [comment]
I can't explain this behavior.  There haven't been any reports of Mount Options not working correctly, but I will retest.

As a workaround, you can remove the btrfs options from SpaceFM's Mount Options and instead add them to udevil.conf.  Adding the following two lines should do it:
~~~~
default_options_btrfs = nosuid, noexec, nodev, noatime, uid=$UID, gid=$GID, compression=lzo, autodefrag
allowed_options_btrfs = nosuid, noexec, nodev, noatime, uid=$UID, gid=$GID, ro, rw, remount, compression=lzo, autodefrag
~~~~
(any options listed in default must be listed in allowed)

**Comment by IgnorantGuru** [comment]
This btrfs options being added to f2fs is not reproducible and I don't see any probable cause for what you describe, unless SpaceFM is identifying the fs as btrfs.  If anyone has more information on such a problem please add comments below.
