### ISSUE TITLE
Keith's MountShareGUI doesn't show any Samba Shares

### ISSUE THREAD

**Issue by EorlBrother** [IgnorantGuru/spacefm#463]
I hope this is the right place to post this, because I didn't find any page from Keith. 

I installed the plugin and it finds every Host in the network. But it doesn't find the Samba Shares of these hosts, the dropdown Menu stays empty. 
When I launch the plugin for the first time in a session, the dropdown menu ist disabled, every later launch has it enabled but empty.

Could this be an issue with the username and password (maybe they aren't used when scanning)?

I'm on Archlinux with linux-ck-ivybridge 3.15.7-1, spacefm 0.9.4, udevil 0.4.3 and smbclient 4.1.9

**Comment by IgnorantGuru** [comment]
Please see Keith's 'Mail me' link [here](http://keithhedger.hostingsiteforfree.com/).
