### ISSUE TITLE
0.9.4 - Unmount & Sync Stuck

### ISSUE THREAD

**Issue by moulei** [IgnorantGuru/spacefm#464]
Specs
SpaceFM 0.9.4
udevil-0.4.3

I looked around and noticed the same problem being reported.

I too am seeing this with the Unmount and Sync sticking when trying to unmount either a usb or flash drive.

Copying something big to a flash stick also happens instantly with no visual of the task manager appearing which is also odd, I'm going to report this on another issue. Because it seems like it's not completed and then if I try to remove the stick with Unmount and Sync it always gets stuck and the only solution I've found is waiting longer to do this, but without any visual cue of the task manager telling me if it's copied or not makes this difficult to judge. As an example, with files as big as 900MB there is no task manager appearing and a 900MB file does not transfer instantly.

I don't see this probem as bad on a usb drive, but I constantly run into it getting stuck as well.

Also another issue I want to report, after unmounting and syncing usb drives in SpaceFM, many times, this is a regular occurance, Windows will tell me there is a problem with the file system and it needs to be checked.

I have seen this problem for several years in SpaceFM, it does not cleanly unmount/sync for some reason.

It is really sad this is not in development, there is a problem here that really needs addressing.

I hope the developer might come back and pick up...

thank you

**Comment by IgnorantGuru** [comment]
Carefully read [this discussion](https://github.com/IgnorantGuru/spacefm/issues/393) and the referenced entries in the User's Manual for the proper use of and behavior of Sync, Unmount, and Remove.  As noted these are system issues.

Please take your questions on the proper use of SpaceFM to a forum.  If you continue to pepper this issue tracker with multiple reports of the same issue, denegration of developers, refusal to accept the decisions of the developers, etc., you will be banned (again).  You have been warned (again).
