### ISSUE TITLE
0.9.4 Copying To Flash Sticks Task Manager Doesn't Appear

### ISSUE THREAD

**Issue by moulei** [IgnorantGuru/spacefm#465]
Specs
SpaceFM 0.9.4
udevil-0.4.3

In relation to issue #464 I mentioned when copying big files to a flash stick the Task Manager never appears.

I can copy the same size file to a usb drive and it always appears. I'm not sure why this happens on flash sticks, but it does so everytime 100% for me reproducible.

So this makes it very difficult to judge when the file has completed copying so the flash stick can be properly unmounted/synced as well.

**Comment by IgnorantGuru** [comment]
Not reproducible - one explanation may be that files complete copying (are closed) but the system is still flushing them to disk.  SpaceFM's taks is complete once the file is closed, so the task manager will disappear or not appear.  This is expected behavior.
