### ISSUE TITLE
After Unmount/Sync Of USB Drives FS Messed Up Needs Check In Windows

### ISSUE THREAD

**Issue by moulei** [IgnorantGuru/spacefm#466]
Specs
SpaceFM 0.9.4
udevil-0.4.3

I can't remember when I saw this reported, but I also see the same problem, when I unmount and sync a usb drive, then plug it back in at some point in time later when using Windows 7, Windows will complain that there is a problem with the drive and it needs to be checked.

Then it will come back saying after the check it found problems and corrected them.

Using SpaceFM daily I typically see this problem every 7-14 days, on average.

This has happend on two different distros and with around 4-5 different usb drives.

Everytime I run into this problem I later test the drives over several times in Windows, but I never run into this issue in Windows. I've also tried different file mangers, Natilus, PCMan, Thunar, and I've never had any problems with them. This only occurs with SpaceFM.

**Comment by IgnorantGuru** [comment]
Not reproducible, and nothing here to indicate a problem in SpaceFM or udevil.  SpaceFM simply writes and closes the files.  It then runs udevil to unmount, which simply runs umount, and sync is literally a sync command.  You can see these commands being issued by running SpaceFM in a terminal.  So any problems encountered with the fs are in the system.
