### ISSUE TITLE
No tooltips/button hints (v0.9.9)

### ISSUE THREAD

**Issue by stevenhoneyman** [IgnorantGuru/spacefm#479]
Not sure if it's a bug or feature request, but I don't see any immediately obvious tooltips on the toolbar buttons, or any way to enable them (or similar e.g. status bar help text). It means it can be a complete gamble what to click on with a bad icon set!

Tested on both gtk2 and gtk3 for #478 f19f178

**Comment by IgnorantGuru** [comment]
Duplicate of #22
