### ISSUE TITLE
Protocol Handlers: try next.

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#483]
Please consider these two features: 
- option to try next appropriate handler if current handler fails (with error, or info message)
- silently try next appropriate handler if current handler fails with specific exit code, so handler author can trigger this.

**Comment by IgnorantGuru** [comment]
No plan to implement these.  A given handler can fall thru to using another solution, but handlers do not fall thru.  They are only ignored if their command for the current function is empty (or contains only blank lines and comments).
