### ISSUE TITLE
Self-contained handler configuration

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#484]
Have you considered storing handler configuration in self-contained predictable dirs?
```
$SPACEFM_CONFDIR/handlers/$HANDLER_NAME/
      ./handler.conf
      ./mount-script.sh
      ./umount-script.sh
      ./info-script.sh
```

**Comment by IgnorantGuru** [comment]
Handlers are stored internally as custom commands, thus their config is part of the SpaceFM session (for efficiency), with associated scripts saved in the scripts folder.  What is lacking in this release is a way to import and export handlers.  One of the next dev tasks in this area will be to design and implement a portable container, probably mimicking plugins.  That way people can share them in the wiki and import them.

**Comment by IgnorantGuru** [comment]
The ability to export and import handler plugins has been added to the next branch, due for 1.0.3 release.  (To test, please see the BUILD NEXT instructions in README.)

This is accessed via the new [Options button](http://ignorantguru.github.io/spacefm/spacefm-manual-next-en.html#handlers-opt) in handler configuration windows.

A note has also been added to the [Plugins Wiki](https://github.com/IgnorantGuru/spacefm/wiki/Plugins) to note that handler plugins may also be shared there.

Any testing is appreciated, including of the normal plugins install and import (to ensure no existing functionality was broken).  Note that handler plugins cannot be installed (as root), but they can be imported via Plugins|Import.
