### ISSUE TITLE
Thumbnail limits by types

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#488]
Please add separate file size limit for thumbnailing for:
- images
- video
- other

Different amount of resources is needed to thumbnail different types of content.
I.e. it is viable to set limit for images to ~4MB, large image processing is resource-heavy. But video limit may be set to some very large number, because video thumbnailer will not read the whole file anyway, and it works with relatively small compressed frames.

**Comment by IgnorantGuru** [comment]
Currently, only images obey the Pic Size limit in Prefs.  videos of any size are thumbnailed.  There is no 'other'.  No plan to change this unless there is evidence that large video files cause a problem (in fact, not theory).  The video thumbnail seek percentage is 25%.

**Comment by IgnorantGuru** [comment]
Also, the default image limit is now 8MB.  Do you think this should be 4MB?

**Comment by Vladimir-csp** [comment]
No, let it be 8MB

**Comment by Vladimir-csp** [comment]
It would be logical to change label in config dialog to indicate that limit is applied to images.

**Comment by IgnorantGuru** [comment]
It says "Max <b>Pic</b> Size To Thumbnail", no mention of videos.

**Comment by Vladimir-csp** [comment]
Sorry, I thought I did a literal translation on this one. I will update it.
