### ISSUE TITLE
Margin/Padding Doesn't Work Right In Detailed And Compact View.

### ISSUE THREAD

**Issue by RaveYoda** [IgnorantGuru/spacefm#490]
OS-Type: Ubuntu 14.04
Window Manager: PekWM
SpcFM Version: GTK3 Hand-Most updated
Screen Size: 1920x1080
ISSUE:
As you see below, the margin or padding could be shrunk by 10%-20%. Examples are marked by white bars inserted. 
![spacefm-to much margin or padding](https://cloud.githubusercontent.com/assets/5226479/7012498/44f4107c-dc77-11e4-8c32-36b278bbb5b9.png)

Were I also to resize the bottom part of the pane to be larger it becomes even more apparent to the excess spacing.
![excess spacing when bottom is just high enough](https://cloud.githubusercontent.com/assets/5226479/7012616/fee0573e-dc77-11e4-8404-4c9fe4dba96e.png)

I don't know though if this would be an easy fix though.

**Comment by IgnorantGuru** [comment]
There is no such padding.  The images you're showing are not square, so they're not filling the vertical space of the row.  If you use thumbnails of images that are taller than they are wide, you'll see this.  I can reproduce no padding on my current GTK2 theme.  If you see any "padding" with tall images, it's probably coming from the theme, but I didn't test this with GTK3.

In compact view, if a full new row doesn't fit, that space will be empty at the bottom. Each row has the height of the large icon size (eg 256), regardless of the aspect ratio of the image in it.

So everything looks correct here.

**Comment by RaveYoda** [comment]
Ahhh, OK, thanks for the info!
