### ISSUE TITLE
ffmpegthumbnailer repo for package maintainers

### ISSUE THREAD

**Issue by itoffshore** [IgnorantGuru/spacefm#493]
I've made a [github repo for ffpmegthumbnailer](https://github.com/itoffshore/ffmpegthumbnailer/releases) for the new functionality in SpaceFM 1.0.0 as the author now hosts [2.0.9 on Google Drive](https://drive.google.com/folderview?id=0B-HAKhnW2w9WQ091bWlDMzFDTmM&usp=sharing#list) which is not suitable for package build scripts.

[SpaceFM](http://pkgs.alpinelinux.org/package/testing/x86/spacefm) is also a package in [Alpine Linux](http://alpinelinux.org/).

**Comment by IgnorantGuru** [comment]
Thanks - you might want to [let them know](https://code.google.com/p/ffmpegthumbnailer/issues/list) about your issue with Google Drive - they did respond to an issue I posted.  But it's not something that has been changing much so your mirror should be reasonable to maintain.  Debian also packages ffmpegthumbnailer.  Seems to be in wide use eg with Thunar.

**Comment by mati75** [comment]
On 2.0.8 is build fine: https://buildd.debian.org/status/package.php?p=spacefm&suite=sid

**Comment by itoffshore** [comment]
The ffmpegthumbnailer author has now migrated to github & also released 2.0.10:

https://github.com/dirkvdb/ffmpegthumbnailer/releases

**Comment by IgnorantGuru** [comment]
Thanks - any indication they quieted the output going to stderr in 2.0.10, or should I add an issue again?  I had added one to their google code site but I don't see it migrated or addressed.

**Comment by IgnorantGuru** [comment]
Oh I do see a "Remove stderr logging" in the [changelog](https://github.com/dirkvdb/ffmpegthumbnailer/blob/master/ChangeLog), so that sounds promising.

**Comment by OmegaPhil** [comment]
I'm testing the latest stable and I'm still getting noise on stderr - I'll see what is going on.

**Comment by OmegaPhil** [comment]
https://github.com/dirkvdb/ffmpegthumbnailer/commit/59522ca5e5097b6e6841fc5dd05f345a8c245cde is the commit of interest - just removes stderr output from a few places in ffmpegthumbnailer itself, rather than the ffmpeg code it wraps.

**Comment by IgnorantGuru** [comment]
@OmegaPhil Thanks for checking.  I have added [a new request](https://github.com/dirkvdb/ffmpegthumbnailer/issues/117) for them on this.

**Comment by IgnorantGuru** [comment]
dirkvdb has silenced the logging messages for the upcoming 2.0.11 - tested okay by OmegaPhil - thanks.

Also, I announced the change of code site on the SpaceFM News page.
