### ISSUE TITLE
XDG bookmark spec

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#494]
Have you considered implementing [XDG bookmark spec](https://wiki.freedesktop.org/www/Specifications/desktop-bookmark-spec/)  in any way? Or you are planning to develop SpaceFM's internal bookmark system without any reference to XDG specs?

**Comment by IgnorantGuru** [comment]
Not a chance.

**Comment by Vladimir-csp** [comment]
...even import, like with GTK bookmarks now?

**Comment by IgnorantGuru** [comment]
I wouldn't mind an import function if it was small enough.  Probably not something I would write.
