### ISSUE TITLE
Failed to mount '/dev/sdb1': Input/output error

### ISSUE THREAD

**Issue by meuwe** [IgnorantGuru/spacefm#497]
Hi,

I compiled 1.0.0 from source and started it for the first time from the command line and I had a USB portable hard drive plugged in when starting SpaceFM and it gave me this output;

```
Selected Device Handler 'Default': MOUNT [*]
Automount: /usr/bin/udevil mount /dev/sdb1 -o 'noexec,nosuid,noatime'
TASK_COMMAND(0x1d7c000)=/usr/bin/udevil mount /dev/sdb1 -o 'noexec,nosuid,noatime'
SPAWN=/bin/bash  /tmp/spacefm-foo-2cc95ea1.tmp/2efa05a4-tmp.sh  run
    pid = 13213
$MFTMirr does not match $MFT (record 0).
Failed to mount '/dev/sdb1': Input/output error
NTFS is either inconsistent, or there is a hardware fault, or it's a SoftRAID/FakeRAID 
hardware. In the first case run chkdsk /f on Windows then reboot into Windows twice. 
The usage of the /f parameter is very important! If the device is a SoftRAID/FakeRAID 
then first activate it and mount a different device under the /dev/mapper/ directory, 
(e.g. /dev/mapper/nvidia_eahaabcc1). Please see the 'dmraid' documentation for 
more details.  udev changed: /dev/sdb1
```

Then I clicked on the hard drive icon below 'View' and I saw my drive listed there, and I clicked on it and a popup appeared showing the same information.

I have udevil 0.4.3 and ntfs-3g-2013.1.13...

SpaceFM 0.9.4 worked just great, never gave me any problems with my usb drives... Hmm

After posting this, I also have another usb drive which is the same, and I plugged it into another port and I then received this error message popup;

```
Failed to write lock '/dev/sdb1': Resource temporarily unavailable
Error opening '/dev/sdb1': Resource temporarily unavailable
Failed to mount '/dev/sdb1': Resource temporarily unavailable
````

**Comment by IgnorantGuru** [comment]
Nothing here to indicate malfunction in SpaceFM, nor any difference in command issued from 0.9.4.  The error messages you're seeing are coming from mount and the mount helper.  You should see the same errors if you mount it manually in a terminal.  Looks like a system or hardware issue, or some ntfs problem.

To see the commands udevil issues to mount so you can test them directly, run:

    udevil --verbose mount /dev/sdb1

**Comment by meuwe** [comment]
It just seemed too odd that right up to the point of starting to use 1.0.0 I see this problem, but never in the past with 0.9.4, so maybe there was an issue, I just found it odd that I didn't get it with 0.9.4, because right before installing 1.0.0 I was using 0.9.4 with my usb drive.

Has there been any changes in 1.0.0 that are more, for a lack of words I can think of, 'More Sensitive' or beter tuned to problems? Like 0.9.4 wasn't seeing a problem, but 1.0.0 did, because of change in it's better performance, code, etc.?

**Comment by IgnorantGuru** [comment]
No, nothing like that.  1.0.0 just gives you more ways to change the commands via handlers, but the default commands are the same.  SpaceFM simply ran udevil as it showed, and it showed you the error received. It doesn't know anything about ntfs except that it's a valid type.

**Comment by meuwe** [comment]
Well I did do a chkdsk in Windows and it found some errors and I reran 1.0.0 and it worked fine. 

Well, what are the chanced that right at that second the drive was bad, seems kind of rare, so makes me wonder why 0.9.4 didn't complain, hmm...

Anyhow...

Can we upgrade from 0.9.4 to 1.0.0 without uninstalling first? Also is 1.0.0 still using /etc/spacefm?

thank you
