### ISSUE TITLE
Setting default compression handler?

### ISSUE THREAD

**Issue by prodigalgvs** [IgnorantGuru/spacefm#501]
I have read the manual, and I cannot find a way to set a default compression handler.  I.e, always have new archives use 7z instead of tar etc.. 

As it stands, for each new file type one wants to compress, one has to choose the handler of choice as the default is always tar.

Update: I am not sure yet, but it appears one has to change an actual option within the handler and choose:
Default | Apply

in order to set the default archiver and have it stick.

On my system (Xubuntu 14.04 amd64) clicking Default | Apply "without" having changed an option the default settings do not stick as it still reverts to tar as the default compressor when one clicks on a new file type.

**Comment by prodigalgvs** [comment]
Update:  I am not sure yet, but it appears one has to change an actual option within the handler and choose:
Default | Apply 

in order to set the default archiver and have it stick.

On my system (Xubuntu 14.04 amd64) clicking Default | Apply <without> having changed an option the default settings do not stick as it still reverts to tar as the default compressor when clicks on a new file type.

**Comment by prodigalgvs** [comment]
Update: I am not sure yet, but it appears one has to change an actual option within the handler and choose:
Default | Apply

in order to set the default archiver and have it stick.

On my system (Xubuntu 14.04 amd64) clicking Default | Apply "without" having changed an option the default settings do not stick as it still reverts to tar as the default compressor when clicks on a new file type.

**Comment by IgnorantGuru** [comment]
When you create a new archive by right-clicking on selected files and selecting New|Archive, you choose the archive type from the drop-down list in the Create Archive dialog (eg Tar xz).

The next time you select New|Archive to create an archive, the archive type you used last time should already be selected - it is the new default.  So that dialog remembers whatever type you created last time.

This is working okay in my tests.  If you find it is not working in some circumstance, please start SpaceFM with a fresh test config:

    killall spacefm
    spacefm -c /tmp/spacefm-tmp-config

Then articulate the exact steps to recreate the problem.

**Comment by prodigalgvs** [comment]
Thank you for your help.  I appreciate it!

It definitely was not working as it should until I changed an option in
the "Configure" window and clicked "Default | Apply" blah blah .. even
after a reboot or shutdown which should do the same thing as the
"kill...." scenario?

Now it is working fine.. so I doubt I will have to go through the steps,
but should I find it doing it again, I will do exactly as you say.
Note:  I had to do the same thing for it to stick to 7z when using
SpaceFM as root.  I did not try any other archiver BTW, but I doubt that
had anything to do with it.

Thanks again!

Gordon VS
gvscheik1@cciwireless.ca

**Comment by IgnorantGuru** [comment]
Starting with a fresh config and choosing New|Archive immediately, I still can't reproduce any problem here.  Clicking Apply in the handler config window shouldn't have any effect.  If anyone can reproduce any problem just add info below and this issue can be reopened.
