### ISSUE TITLE
Compact view fails to scroll to selected file under some circumstances

### ISSUE THREAD

**Issue by OmegaPhil** [IgnorantGuru/spacefm#502]
* Window too small to display whole directory in compact view.
* Search on substring of a filename out of view, but not the first characters of the name.
* Or, select last file in view, press down to move selection to next file in next column.

In both cases, the selection moves but the viewport doesn't scroll.

This appears to have been fixed in [this upstream bug patch](https://bugzilla.xfce.org/show_bug.cgi?id=6014#c11), however this introduces a behaviour change that might not be appreciated - now when the scroll happens, only just enough scrolling is done to bring the selected file into view, not scrolling to bring as much of the relevant column into view as possible.

This means that if you play with the 3rd point above, and have the next column contain filenames of increasing length, every length increase triggers a scroll - is that acceptable?

I have adapted the patch so that it applies to SpaceFM and will sit on it for a week to see if anything else breaks.

**Comment by IgnorantGuru** [comment]
I don't think I can reproduce this in GTK2 - does this problem exist in GTK2, GTK3, or both?

jfyi, SpaceFM doesn't really have an 'upstream' when it comes to exo.  Early PCManFM borrowed some exo code from thunar but it's essentially forked.  Not to say you can't incorporate upstream fixes, but just note that it's on its own track, with some SpaceFM-specific bugfixes and adjustments mixed in there.

Do you have a test branch where I can see the fix applied?  When I search for the start of a filename, I do get a horiz scroll such that the full filename comes into view, so having trouble reproducing this.  Do any other settings or modes apply?

**Comment by OmegaPhil** [comment]
OK, the popup search problem does seem to be inconsistent (but something triggers it consistently when it happens). The window needs to be normalised (so in my case it covers ~50% width-wise of the screen, height maxed).

The problem of scrolling to the selected file when moving down off the last visible file is consistent here - breaks in gtk3 as well.

See the WIP commit here: https://github.com/OmegaPhil/spacefm/commit/c6ed68cbdb00f8b63fa333a8f396a284d2f24220

The key for me was the exo_icon_view_scroll_to_item if block comment 'the second condition above is to make sure that we don't scroll horizontally...' - as soon as I started to fiddle with that it worked, I then later noticed that the source had been further fixed 'upstream' (yeah I did notice a tiny change in your code that I incorporated).

**Comment by OmegaPhil** [comment]
Sorry for the delay - I got 0 notifications from github on this even though I'm 'subscribed'.

**Comment by IgnorantGuru** [comment]
Okay, I'd appreciate you making any changes you think are suitable here, including any general upstream fixes/updates you think should be applied.  I don't use that view style so I'm not likely to notice the finer issues.  Do note that both Icon and Compact views use that exo code, so changes should be tested in both view styles, with Large Icons enabled and disabled, GTK2 and GTK3 (with Adwaita themes as the normal).  Just do a pull request or let me know it's ready and we'll bring this into next for testing.  Thanks for the info.

**Comment by IgnorantGuru** [comment]
Also, if it repeats please notify github support and me about the lack of notifications - thanks.

**Comment by OmegaPhil** [comment]
I got that notification at least ;) But not the prior one. Can you respond to this?

**Comment by IgnorantGuru** [comment]
bump

**Comment by OmegaPhil** [comment]
Nope - contacting support now.

**Comment by OmegaPhil** [comment]
Not that it matters for this ticket, but apparently one of their mailservers noticed startmail was dropping mails, so stopped delivering to that domain - this should be resolved now.

**Comment by IgnorantGuru** [comment]
Thanks for reporting to them and please let me know if any problem continues.

**Comment by OmegaPhil** [comment]
Hmm, the new changes refuse to compile under GTK3 here (does the build system seriously not notice such a huge change?? Am I only seeing this now due to a manual clean??), the first error I'm looking into is:

```
In file included from /usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h:9:0,
                 from /usr/include/glib-2.0/glib/gtypes.h:32,
                 from /usr/include/glib-2.0/glib/galloca.h:32,
                 from /usr/include/glib-2.0/glib.h:30,
                 from /usr/include/gtk-3.0/gdk/gdkconfig.h:13,
                 from /usr/include/gtk-3.0/gdk/gdk.h:30,
                 from /usr/include/gtk-3.0/gtk/gtk.h:30,
                 from exo/exo-icon-view.h:36,
                 from exo/exo-icon-view.c:46:
exo/exo-icon-view.c: In function ‘exo_icon_view_get_item_needed_size’:
exo/exo-icon-view.c:4890:34: error: ‘GtkCellRenderer’ has no member named ‘visible’
       if (G_UNLIKELY (!info->cell->visible))
```

Comparing '/usr/include/gtk-2.0/gtk/gtkcellrenderer.h' to '/usr/include/gtk-3.0/gtk/gtkcellrenderer.h', I can see in GTK3's case _GtkCellRenderer is almost empty, whereas in GTK2's case there is definitely a visible member (surrounded by some unknown macro). There is a 'visible' GObject property available, but that requires a special function to get and set right?

I just want to sanity check my understanding here before I start hacking with the code.

**Comment by IgnorantGuru** [comment]
I don't think that would be the build system.  Their patch goes beneath the GTK API to get at that property.  The data beneath the API does indeed vary from GTK2 to GTK3.  Since SpaceFM supports both versions, you'll probably need to ifdef the relevant code sections.  eg:

~~~~
#if GTK_CHECK_VERSION (3, 0, 0)
   // your gtk3 compatible code
#else
   // your gtk2 compatible code
#endif
~~~~

For example, you can see this used [here](https://github.com/IgnorantGuru/spacefm/blob/55588f112e01d51c355f2c99b1ada6efb7ba1e8c/src/desktop/desktop-window.c#L484).

Or in some cases, you can use the gtk2-compat.h file, which translates some of the GTK2/3 API centrally.  Though it doesn't sound applicable in your case.

Odd though - is thunar still using gtk2?

**Comment by OmegaPhil** [comment]
As long as I'm correct in understanding that error thats fine - both versions have gtk_cell_renderer_get_visible so I'll start using that.

Thunar doesn't look to be ported to GTK3 - there is a 2012 GTK3 branch associated with a core programmer in git, but another programmer has a much more uptodate repo with no such branch, and the configure.ac.in is only interested in GTK2 there.

**Comment by IgnorantGuru** [comment]
I changed the above example to a clearer one at [line 534](https://github.com/IgnorantGuru/spacefm/blob/55588f112e01d51c355f2c99b1ada6efb7ba1e8c/src/desktop/desktop-window.c#L534) -my original one was a function declaration which might be confusing.

Yes I think you're interpreting the error correctly - I don't think their GTK2 patch will work as is in GTK3.

**Comment by OmegaPhil** [comment]
OK, this has passed testing and is now working with both GTK2 and 3, sitting on it for a week.

**Comment by OmegaPhil** [comment]
This definitely Works For Me, needs more feedback from others, depending on the consensus it might be worth forcing it to show as much of a column as possible again, but that risks triggering bugs they solved when they made this change.

**Comment by OmegaPhil** [comment]
Merged, closing this for now.
