### ISSUE TITLE
Strange ratio when second panel opens 1st time

### ISSUE THREAD

**Issue by amarao** [IgnorantGuru/spacefm#503]
One the large screens when 2nd panel is opened, it takes most of the screen space. May be proper way is to open it in half-half size?

Here how it looks on the large screen: http://i.snag.gy/in8PP.jpg

version: 0.9.4-2
xfce4 @ ubuntu15.04

**Comment by IgnorantGuru** [comment]
iirc SpaceFM uses a new panel width of 50% of the window size when the window is first opened, not 50% of the current size.  There were some tricky issues with this.  Not planning to change this as it only affects the first time the panel is shown and the current behavior was chosen as a reasonable best, but thanks for bringing it to my attention.

**Comment by amarao** [comment]
I've checked it now:

rm -r ~/.config/spacefm
spacefm

It opens maximized, but still is making 2nd panel much larger than 1st.
