### ISSUE TITLE
Panels 2, 3, &4 do not keep sidebar condition when they are the only panel open.

### ISSUE THREAD

**Issue by prodigalgvs** [IgnorantGuru/spacefm#506]
Steps to repeat:
1) Open panel 2 and set its sidebar condition to "treeview"
2) Close panel 1. Notice that sidebar condition of panel two has reverted to "bookmarks."
3) Reopen panel 1.  Notice that panel 2 sidebar is back to "treeview"

Another:
1) Open panel 3.
2) Set whatever sidebar conditions you want for panel 3.
3) Close panel 1.  Sidebar for panel 3 will be closed.
4) Reopen panel 1, and sidebar for panel 3 is back to what was set in step 2.

One can mess with this in many combinations, but it is always the same.  The only panel to retain sidebar condition if it is the only panel open is panel 1.

**Comment by IgnorantGuru** [comment]
Please [read the manual](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#gui-pan-mem) on the proper behavior of the panel memory.  The behavior you describe is correct.

**Comment by prodigalgvs** [comment]
It may be correct, but it is ultra annoying. And pretty much useless.

If one cannot switch a specific panel to a single view and have it keep
its condition then why have them?  One might as well just switch the
view in panel 1 and forget about using more than one panel.

Just because it is designed that way does not make good design. It isn't.

**Comment by prodigalgvs** [comment]
One more point I think needs to be said:

A user should not have to delve into the manual to discover how a
feature works before they use it.  It should be at least somewhat
intuitive on first blush.  If it is not intuitive then it is perfectly
natural to be seen as a bug.  And trust me, this panel issue is counter
intuitive.

I mean, what good is tree view unless it is in a single window? etc..

Your comments make users feel stupid.

**Comment by prodigalgvs** [comment]
And finally... some of us just want to use a product.  We do not want to
have to read manuals and back trace issues all day. You act as if you
expect those who report issues to have done all the tracing for you or
they should not bother to report.

You are the developer.  The tracing is your job, not the users.  You act
as if every issue reported is a personal insult.

I love the product. So I keep using it.  But I doubt I will bother to
report issues any more.  I am tired being treated like I am an idiot.

**Comment by VastOne** [comment]
... and we wonder why sabbaticals are needed

**Comment by IgnorantGuru** [comment]
@VastOne And we wonder why some people get banned from the issue tracker, no matter how many identities they use (in this case, "prodigalgvs" + "ghost" + "meuwe", etc).  In fact, this is the only person I have ever banned - most people are very helpful.  Unfortunately this is one of those people who wants constant attention and will do anything to create it.   They distract and detract from the project far more than they contribute, and he/she has been doing so for years.  This person has been warned repeatedly, and etiquette has been fruitlessly discussed.  The attacks from this person are so orchestrated and repetitive that I really wonder what the source of it is.

Apparently I will need to contact github to see if we can find a way to ban the IP and track how many user accounts this person is misusing on github.  prodigalgvs, you've been warned.  Get lost - your participation is NOT welcome on this project.  Stop wasting our time.

**Comment by VastOne** [comment]
@IgnorantGuru Well said... 

The repetitive nature of prodigalgvs's rant was a dead give away.  It is really simple, either be a part of the problem or part of the solution, if you choose to be a part of the problem then get the hell out of our way

Hopefully github will have the resources in place to ban a pest
