### ISSUE TITLE
support hotkeys cyrillic?

### ISSUE THREAD

**Issue by pvlb** [IgnorantGuru/spacefm#510]
Hi!
Pls, add support hotkeys cyrillic. Please add or multi hotkeys or unify.
Hotkeys work only in Latin or Cyrillic keyboard layout (after the design mode). This is very inconvenient. Please fix it.

**Comment by Vladimir-csp** [comment]
This bugs me too, as in most of the software I come across keybindings work regardless of layout.
But I remember that @IgnorantGuru already rejected the similar bug.

**Comment by IgnorantGuru** [comment]
Duplicates #57
