### ISSUE TITLE
--with-preferable-sudo

### ISSUE THREAD

**Issue by jagajaga** [IgnorantGuru/spacefm#516]
As I was talking in https://github.com/IgnorantGuru/spacefm/issues/452 I have pkgs in different places.
I'm setting `--with-preferable-sudo={sudo path}` but I can change only `graphical su` to my `sudo path`. How can I change `terminal su`?

**Comment by IgnorantGuru** [comment]
There isn't currently a way to do that.  I'll consider adding the custom one to the Terminal SU list, or maybe there should be options for both.  In the meantime you could hack the source for that pretty easily, just replace all occurrences of the sudo path.

**Comment by IgnorantGuru** [comment]
New options have been added to /etc/spacefm/spacefm.conf to allow setting terminal and graphical su programs.  See #577 for full details.
