### ISSUE TITLE
Spacefm does remember compression handler after extraction of archive

### ISSUE THREAD

**Issue by HerborenInVlammen** [IgnorantGuru/spacefm#517]
The new version does not remember compression handlers well.   To reproduce do the steps.

Chose an archiver other than TAR such as 7z
Compress a file or folder (at this stage compression handler is remembered)
Extract any archive anywhere
Attempt to compress a file or folder. After extraction of any archiver the compression handler is back to TAR

This is confirmed on Ubuntu 14.04 as well as Peppermint 5

**Comment by IgnorantGuru** [comment]
Thanks, confirmed when using Extract To (not Extract).

**Comment by IgnorantGuru** [comment]
This should now be fixed - please see BUILD NEXT instructions in README for testing instructions.
