### ISSUE TITLE
Hotkeys do not work if keyboard layout different from EN is chosen

### ISSUE THREAD

**Issue by Temp24354** [IgnorantGuru/spacefm#520]
I use two keyboard layouts: ru and en. I switch them using setxkbmap, and when RU is chosen, spacefm doesn't react on any hotkeys being pressed.

**Comment by IgnorantGuru** [comment]
Closing as a duplicate of #57.  Note that you can still set custom keys and user them, just the default ones won't work.

**Comment by Temp24354** [comment]
So, it is impossible to fix this bug in Spacefm's code, isn't it?

**Comment by IgnorantGuru** [comment]
No, this may be fixed soon - maybe in the next release - subscribe to #57 for updates and you can help test any fix when it's ready.

**Comment by Temp24354** [comment]
Thank you very much.
