### ISSUE TITLE
Single Right Click Opens Bookmark in New Tab/Long Right Click Opens Menu

### ISSUE THREAD

**Issue by arclance** [IgnorantGuru/spacefm#521]
After updating spacefm if found that bookmark use has changed noticably.
Single (Short) right clicks open the bookmark in a new tab but a long click opens the bookmarks right click menu.
This is confusing and inconsistent with the rest of the spacefm.

I also no longer seem to be able to add commands to the bookmarks right click menu which is a regression from the previous behavior of spacefm.

My bookmarks are also gone though that may just be a necesary part of the update.

When recreating my bookmarks I found that underscores "_" are removed from the display name assigned to bookmarks when displayed in the sidebar. ("Data_1" becomes "Data1")

**Comment by IgnorantGuru** [comment]
Thanks - this is a very unusual report, as it contains multiple non-reproducible aspects.  Be sure you are testing SpaceFM with a default Adwaita theme, that no other software is interfering, etc.

> After updating spacefm if found that bookmark use has changed noticably.
> Single (Short) right clicks open the bookmark in a new tab but a long click opens the bookmarks right click menu.
> This is confusing and inconsistent with the rest of the spacefm.

That is not the intended behavior.  A left click opens, a right click shows the menu.  Nothing fundamental was changed about the click event handlers in that pane.

> I also no longer seem to be able to add commands to the bookmarks right click menu which is a regression from the previous behavior of spacefm.

Right click on bookmark and select New|Command.

> My bookmarks are also gone though that may just be a necesary part of the update.

No, bookmarks should have been imported from the bookmarks file.  It sounds like you may have a non-standard configuration, so please test with a default configuration.

>  When recreating my bookmarks I found that underscores "_" are removed from the display name assigned to bookmarks when displayed in the sidebar. ("Data_1" becomes "Data1")

Correct.  Underscores are used in menu item names to denote key shortcuts and are stripped when the name is displayed in other contexts.

Nothing here can be reproduced or is actionable in its current state.  You'll need to provide clear reproducible steps from a default configuration and theme.  On the click problem, a different mouse may help, sounds like a low-level issue with GTK not responding correctly to your hardware, at least as SpaceFM uses it.  I doubt this is an issue that can be corrected in SpaceFM's code.

Feel free to add more info and this issue can be reopened if needed.

**Comment by IgnorantGuru** [comment]
> I also no longer seem to be able to add commands to the bookmarks right click menu which is a regression from the previous behavior of spacefm.

On this, now I see what you are saying...  The Design Mode can be used on some items in the new right-click menu of bookmarks.  The Open item and Settings submenu, and items within the Settings submenu, can have commands added to them.  This is noted in the manual.

**Comment by arclance** [comment]
Thanks - this is a very unusual report, as it contains multiple non-reproducible aspects. Be sure you are testing SpaceFM with a default Adwaita theme, that no other software is interfering, etc.
Adwaita is a GTK3 theme I use GTK2.
I don't use GTK3 unless there is no other option because of the theme issues with themes that are not Adwaita that crop up in any GTK3 program periodically.


    Right click on bookmark and select New|Command.
This adds a new command to the bookmarks section of the left pane and not the bookmarks right click menu.

    No, bookmarks should have been imported from the bookmarks file. It sounds like you may have a non-standard configuration, so please test with a default configuration.
They were not.
What default configuration?
Also a default configuration would come with a default set of bookmarks so how could you test the importation of user created bookmarks from previous versions of spacefm this way?

    Correct. Underscores are used in menu item names to denote key shortcuts and are stripped when the name is displayed in other contexts.
They were not treated this way in pervious versions of spacefm (for bookmarks at least) so this is a regression necessary or not.

**Comment by arclance** [comment]
The right click issue was theme related, I found similar problems mentioned from pcmanfm users.
https://bbs.archlinux.org/viewtopic.php?id=95173

Adding this to the theme to have the menu created five pixels right of the click point stopped GTK2 from sometimes incorrectly selecting the first item in the newly opened menu.
```GtkMenu::horizontal-offset = 5```

The odd thing is that the only time this has ever happened to me was with the new bookmarks pane in spacefm and nothing else not even older verisions of spacefm.

**Comment by IgnorantGuru** [comment]
Thanks for the followup.  On this...

> They were not.
> What default configuration?
> Also a default configuration would come with a default set of bookmarks so how could you test the importation of user created bookmarks from previous versions of spacefm this way?

To test this, copy your 1.0.0 config directory to a temporary copy and start spacefm 1.0.1 with the copy (--config-dir).  This should import the bookmarks from the 'bookmarks' file in that config dir into the new Bookmarks menu.

To use a default configuration for the test, run spacefm 1.0.0 with --config-dir on a dir that doesn't exist, to create a new config dir, and add some bookmarks.  Then run 1.0.1 on that config dir to see upgrade behavior.

You can also just use the Import|GTK Bookmarks, which imports ~/.gtk-bookmarks in a similar way.  Overall there's not much to fail there, which is why I suspect your bookmarks file was not a normal configuration.  Yet if you can provide steps to reproduce a problem upgrading a default 1.0.0 configuration, please open a new report with the exact steps.  Thanks.

**Comment by arclance** [comment]
To test this, copy your 1.0.0 config directory

I was moving from the last 0.9.x next branch commit not 1.0.0 maybe that was the problem.
I was busy and did not have a pressing reason to update until OmegaPhil asked me to test if his fix for the memory use problem I have (#346) worked.

    This should import the bookmarks from the 'bookmarks' file in that config dir into the new Bookmarks menu.

If that was not the problem there is a bookmarks file in my ~/.config/spacefm folder with my old bookmarks in it but it was not imported.

    You can also just use the Import|GTK Bookmarks, which imports ~/.gtk-bookmarks in a similar way. 
I don't think my old spacefm bookmarks and gtk-bookmarks are identical so I don't think that would have helped.

I backed up my config before updating so I can still see what my bookmarks were so recreating them was not a problem.

**Comment by IgnorantGuru** [comment]
A potential fix for the right-click on Bookmarks select Open on the menu, which also affects GTK3 eg #529, is in next.  Works for me.

These was a fix for a GTK bug in menu's event handling that activated a menu item on button release because GTK didn't always activate it.  This new bug seems to be caused by GTK sending the release event to the menu.

**Comment by arclance** [comment]
That works for me with GTK2 using

    GtkMenu::vertical-padding = 0

 (the default) in my theme.
I will keep using the 

    GtkMenu::vertical-padding = 3 

workaround in case some other program might have this problem in the future though.
