### ISSUE TITLE
No way to escape underscores in bookmark item names

### ISSUE THREAD

**Issue by arclance** [IgnorantGuru/spacefm#522]
Before the recent bookmarks change (after 0.9.x ?) underscores in bookmark display names were shown in the interface.

There is currently no way I can find to escape underscores (_) in bookmark item names so they are shown instead of suppressed when displayed by the interface.
This is troubling since it is impossible to make a bookmark for a particular device or partition with a underscore in its assigned drive label to have its associated bookmarks displayed name match its actual drive label.

Adding a way to escape or subsitute a recognized standin for the underscore character would allow users to display underscores in bookmark names if they wish to.

**Comment by IgnorantGuru** [comment]
The next branch allows \\_ as an escape for underscores in all item names (menu items, toolbar items, bookmarks, etc.)  When this escape is used, any unescaped underscores will still vanish, and the name will not have a mnemonic set in menus.

Please let me know if that doesn't work correctly in any functions.

**Comment by arclance** [comment]
Seems to work fine but I am only using it to show underscores in bookmark names right now.
If I run into any problems I will let you know.
