### ISSUE TITLE
Spacefm always tries to connect to ftp:// using 21 port, even if I explicitly set another port

### ISSUE THREAD

**Issue by Temp24354** [IgnorantGuru/spacefm#523]
One of my devices runs ftp server on 2221 port. If I type "ftp://192.168.1.113:2221" into spacefm adress bar, I get error: "Error connecting to ftp: Failed to connect to 192.168.1.113 port 21: Connection refused", which is obvious, because there is no server on 21 port. If I use "File -> Open URL" menu, behavior is the same. Could you please fix it?

**Comment by IgnorantGuru** [comment]
There does seem to be a problem with the default ftp handler with a port spec.  As a workaround, you can use udevil instead.  To do so, install udevil, then go into Devices|Settings|Protocol Handlers and move the 'ftp' handler down to the bottom of the list (so udevil is above it in the list).

**Comment by Temp24354** [comment]
By some reason connection is very slow. Now I use Udevil, it mounts my ftp-server using fuse (curlftpfs), and it takes Spacefm about 20 seconds to load contents of ftp-server's root, though server is based in my local network and is accessed via fast Wi-Fi connection. When I browse it using command-line utilities it is still very slow. Probably, curlftpfs itself should be replaced?

**Comment by IgnorantGuru** [comment]
This has been corrected in the next branch, due for 1.0.2 release.  If you have modified your 'ftp' handler, you'll need to select it and click the 'Defaults' button to bring in the new default handler.

Afaik curlftpfs is the generally preferred solution for mounting ftp, replacing the old ftpfs.  You can test other software by adding custom handlers.

**Comment by Temp24354** [comment]
Thank you.
