### ISSUE TITLE
version 1.0.1, tree view hangs

### ISSUE THREAD

**Issue by dragonauta** [IgnorantGuru/spacefm#525]
HI, I'm using ArchLinux + openbox + spacefm 1.0.1-1 (from official repos)
I installed [Super-Flat-Remix](http://the-ilife.com/post/127) icons under my user .icons folder and activated through lxappearance.
All applications looks good, but spacefm hangs when activating tree view.
It puts cpu at 100%  for a couple of minutes and then shows the tree view, but if I clic on a folder it hangs again.
Thanks

**Comment by dragonauta** [comment]
Sorry, my bad.
Super-Flat-Remix doesn't follow Freedesktop specifications.
Replaced for Ultra Flat theme from AUR and now works.
Please close this issue

**Comment by IgnorantGuru** [comment]
Thanks for the report - not very reasonable behavior even if the package wasn't freedesktop-compliant.  Yet SpaceFM doesn't directly read the icons from there, it does so through gdk, etc.  So that's where the CPU usage was likely coming from.
