### ISSUE TITLE
New symbol lookup error on latest release after latest sid dist-upgrades

### ISSUE THREAD

**Issue by VastOne** [IgnorantGuru/spacefm#526]
spacefm: symbol lookup error: /usr/lib/x86_64-linux-gnu/libutvideo.so.15: undefined symbol: fdLogSock

Will not let me get a version of spacefm (spacefm --version)

Debian, SID, latest SpaceFM from that environment

**Comment by IgnorantGuru** [comment]
Thanks but this probably needs to be reported to the Debian package manager, @mati75, through their bug tracker.

**Comment by VastOne** [comment]
Will do ... seems related somehow to a cmake bug, will keep you updated

Thanks

**Comment by VastOne** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=785273

**Comment by VastOne** [comment]
For closure... update to libutvideo15 just came through and resolved this issue
Will make sure to send bug reports to correct place next time

Thaks

**Comment by mati75** [comment]
@VastOne It look like for ffmpegthumbnailer error, not for spacefm. I will look for that.

**Comment by mati75** [comment]
@VastOne libutvideo15 not exists in Debian repository, it is deb-multimedia repository problem. Everything is fine with spacefm in unstable.
