### ISSUE TITLE
Trouble with Bookmark Submenu in latest build: 1.0.1+201505140731.966~ubuntu14.04.1

### ISSUE THREAD

**Issue by HerborenInVlammen** [IgnorantGuru/spacefm#527]
If one creates a submenu off of the main "Bookmark" entry (at the top), every time Spacefm is opened it automatically opens to said submenu and not the main bookmarks sidebar.

**Comment by IgnorantGuru** [comment]
The Bookmarks pane will follow the current dir if option [Follow Dir](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#gui-book-side) is enabled.  That is probably why you're seeing that behavior.  If not feel free to add more info below.

**Comment by HerborenInVlammen** [comment]
You are correct about the follow dir option.  Thank you.
