### ISSUE TITLE
Cannot set custom icons for bookmarks

### ISSUE THREAD

**Issue by HerborenInVlammen** [IgnorantGuru/spacefm#528]
No matter what bookmark, icon type (png, jpg, svg etc.), or location, spacefm will not show any custom icons for bookmarks, submenus etc..  Tried to make this work for an hour.  Nothing.

Using:  1.0.1+201505140731.966~ubuntu14.04.1

**Comment by IgnorantGuru** [comment]
To set a custom icon, right-click on a bookmark and select Properties.  Then enter the icon name (eg "gtk-add") in the Icon box.  For testing, try stock GTK icons (gtk-add, gtk-remove, etc, or "spacefm").  Icons are loaded from your default GTK icon theme, and GTK will generally find 3rd-party icons installed to standards dirs.

If that's still not working, are customized icons show in the Bookmarks menu, the Bookmarks pane, or neither?  Does the Settings|Bookmark Icon setting have any effect?

**Comment by HerborenInVlammen** [comment]
Hi:

As per the other bookmark issues I posted, the problem seems to occur
only with today's daily build.  Reverting back to yesterday's daily
fixes it.

**Comment by IgnorantGuru** [comment]
I'm not following why you say you can't set custom icons in particular, unless you just mean you can't open the right-click menu due to #529.  I'm assuming that's the problem and closing this as a duplicate - that probably needs to be resolved first.

Also note that you can right-click on a bookmark in the Bookmarks menu, or use [design mode shortcuts](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#designmode-shortcuts) to change the icon.

**Comment by IgnorantGuru** [comment]
Actually this doesn't sound like #529 so reopening, but you'll need to provide the info requested above if this is still a problem - thanks.

**Comment by HerborenInVlammen** [comment]
Sorry. At work.
Due to #529 it was very difficult to access the right-click menu in the sidebar.  But holding the right-click mouse button down and using arrow keys was able to access menu.  I should have made that clear earlier.

Anyway, then even entering gtk-add as icon name for example, did not work.

Now I have gone back to earlier daily build and have no problems.  Maybe the daily build did not build right on install.  Whatever.  It did not work.  I know sometines these things happen.

**Comment by HerborenInVlammen** [comment]
Just installed daily build 1.0.1+201505150731.981~ubuntu14.04.1 and everything works fine as far as the sidebar and bookmarks goes.  Not sure what the last build did on my system, but it is irrelevant now.

Also, love the new toolbar design and so on!  Thank you.

**Comment by IgnorantGuru** [comment]
Thanks for the followup and feedback.
