### ISSUE TITLE
PLEASE TEST: New Icon Chooser [GTK2 only]

### ISSUE THREAD

**Issue by IgnorantGuru** [IgnorantGuru/spacefm#532]
The 'next' branch, due for 1.0.2 release, now includes an icon chooser.  Any place you type an icon name into SpaceFM, you should now see a Choose button.  The icon of the choose button should match the icon entered in the text box, and will change as you change the text.

The GTK3 build of SpaceFM will currently have the Choose button disabled (except it will still show the icon).  That code is still being resolved.

Much thanks to @OmegaPhil who researched the exo_icon_chooser_dialog used in Thunar and helped import the code into SpaceFM.  With a few unneeded things trimmed out, there was not much cost in executable size increase - about 60KB.

Thanks for any testing with this and you can add any problems or questions below.  To install the next branch, please see the BUILD NEXT instructions in [README](https://raw.githubusercontent.com/IgnorantGuru/spacefm/master/README).

**Comment by arclance** [comment]
I changed the icon displayed for the header of the Bookmarks pane that reads "Bookmarks".
I had to close and reopen the spacefm window for the icon to change to the newely selected one but otherwise it worked fine.

**Comment by Vladimir-csp** [comment]
It loads slow, locks GUI while loading, but apart from that it looks and works good.

Minor issue with parent properties dialog: target text area is not graphically highlited, "Browse" button is placed in the middle of nowhere.
![prop](https://cloud.githubusercontent.com/assets/4061903/7902911/b4bfb218-07d2-11e5-9781-7609aff07953.png)

**Comment by IgnorantGuru** [comment]
Changing the main Bookmarks icon should now update the icon.

I added a busy cursor for loading the icon chooser.

> Minor issue with parent properties dialog: target text area is not graphically highlited, "Browse" button is placed in the middle of nowhere.

The border and shading of the GtkTextView is theme dependent.  Even in your screenshot some shading of the box is barely visible.

**Comment by Vladimir-csp** [comment]
> Even in your screenshot some shading of the box is barely visible.

it is barely visible even in Adwaita (no border, just very slightly different background), but on my screenshot it is not visible at all.
Is there a way to encapsulate it in some other border?

**Comment by IgnorantGuru** [comment]
> Is there a way to encapsulate it in some other border?

I have added a shadow of type GTK_SHADOW_ETCHED_IN to the scroll window containing the text view.  This seems to make it more reasonable.
