### ISSUE TITLE
lxterminal spawned by spacefm turns into a zombie process

### ISSUE THREAD

**Issue by SeaWolfArch** [IgnorantGuru/spacefm#533]
This is with Arch Linux, Openbox, SpaceFM 1.0.1.

How to reproduce:

- right-click on a zip archive,
- choose "List Contents" in the submenu, the content of the archive appears in a lxterminal window,
- hit 'Enter' to close the terminal window.

The lxterminal window closes but its process is still there, it is now a zombie.

This doesn't happen if I choose xterm as a terminal for spaceFM.

**Comment by IgnorantGuru** [comment]
Thanks, this should now be fixed in next branch, due for 1.0.2 release.

**Comment by ncmprhnsbl** [comment]
just confirming fixed in 20150523 build in arch + openbox
