### ISSUE TITLE
SpaceFM gets stuck if reopened after a removable drive is plugged off

### ISSUE THREAD

**Issue by HisDudeness3008** [IgnorantGuru/spacefm#539]
I'm sorry if this issue has alrready been reported, I'm new here and didn't know exactly how to look for it.

Upon exit, SpaceFM saves my opened tabs and reopens them as I launch the File Manager another time.

The problem is, if a removable drive is mounted, and its root directory opened in a tab, if I remove the drive while SpaceFM is closed, it will get stuck if launched again, with the following error:

> **Error**
> 
> Unable to access *mountpoint*
> Permission denied

After closing this dialog by clicking on the Ok button, the only one present, SpaceFM will answer to no action: trying to launch it again will not give the dialog anymore, but won't just give any sign. Not even plugging the drive back again will solve things. I have to kill SpaceFM with the terminal. After this, if I launch SpaceFM again, the removable drive's tab will still be opened, but it will be pointing to my home filder instead, even if another tab is opened there.

# Details:

* Launching SpaceFM while the Error dialog is still open will just open a new shaded session every time: only the title bar, pointing to my home folder, and the menu bar will be visible. Instead, after closing the dialog nothing will happen, and trying to close those shaded instances will reveal SpaceFM to be not responding.

* The shaded window can be expanded to show a complete SpaceFM window. It will flawlessly navigate until the Error dialog is opened, but as soon as the Ok button gets pressed, it will stop responding. In this window, the Devices tab won't show, even if enabled. Disabling it and enabling it back again will get it to show.

* If a shaded window is opened while the Error dialog shows, upon killing SpaceFM and relaunching it, the windows which get opened will be shaded as well, with the Devices tab not showing again. The problem will be solved the same way.

* The error occurs both if the drive is brutally unplugged or if it is unmounted in the terminal (using sudo umount) while SpaceFM is closed

* **The error occurs only if the root directory of the drive is opened in a tab**. If a subfolder in the drive is opened instead, SpaceFM will give no problems if the drive is missing upon relaunching. The home folder will be opened in its place.

* The problem will occur both if the drive's tab is the only one opened or if there are other tabs. It will occur if the drive's tab was on focus or if any other was opened upon closing SpaceFM, and both if that tab was on the far left, far right or any other position.

* The problem will take place both if there is only one tab located in the drive's root folder opened or if there's more than one (or even if those other tabs are opened in some subfolder of the drive)

* Even if doing the exact same things which will trigger the error, the issue won't occur (apparently randomly) once in a while.

# System details:

I'm running Arch Linux x64 with openbox as my WM and DE. No DM is installed. I'm using the latest Git version, updated today (23/05/2015). The problem took place with previous versions as well.

Hope this helps, if more details about my system or how I did these tests are needed, just ask me. And thanks for this awesome file manager!

**Comment by IgnorantGuru** [comment]
Thanks for your detailed report.  This hang, introduced in 1.0.0 f167b28, will actually occur when any access-denied dir is passed on the command line or loaded from a saved tab.  This should now be fixed in the next branch, due for 1.0.2 release.  You can test using spacefm-git in the Arch AUR.
