### ISSUE TITLE
If a Key Shortcut is assigned to the "Extract To" command, it will attempt to extract non-archives if key shortcut is is used.

### ISSUE THREAD

**Issue by HerborenInVlammen** [IgnorantGuru/spacefm#540]
A minor bug:

If a Key Shortcut is assigned to the "Extract To" command, it will attempt to extract non-archives if said key shortcut is is used.  I.e., if any file type is selected that is not an archive, using the key shortcut will summon the "Extract To" dialogue anyway.

This does not occurr with the "Extract" command.

This is on the latest "next" build (that I first noticed it).

**Comment by IgnorantGuru** [comment]
It's always possible to select non-archive files along with archives, even when using the menu item Extract or Extract To, as only the MIME type of the first selected file determines menu context.  In that case, SpaceFM will extract files for which it has an archive handler, and will merely print a warning to stderr for the other files (as an aid to debugging archive handler commands).

When you activate Extract or Extract To by keyboard, it does the same thing.  So I think it attempting to extract any selected archive files when you activate Extract To is a reasonable response.  You will note that Extract does the same when activated by key shortcut if you run spacefm in a terminal.

@OmegaPhil may have a different opinion but I think this is reasonable behavior.

**Comment by IgnorantGuru** [comment]
@OmegaPhil Only thing I do notice here is that SpaceFM still executes a command even when all selected files have no handler.  This should probably be corrected, even though the command run does nothing

~~~~
TASK_COMMAND(0x107d9a0)=fm_handle_err() {
    fm_err=$?
    if [ $fm_err -ne 0 ]; then
       echo; echo -n '[ Finished With Errors ]'
       exit $fm_err
    fi
}
~~~~

**Comment by OmegaPhil** [comment]
The reporter is saying its worse than that though - I can assign a shortcut to Extract To, select a single text file and still get the dialog come up asking where to Extract To, similar for the Extract command. Thats stupid, and presumably only happens because the filtering logic just happens through the GUI (I'm assuming). Currently I'm looking into the code to see how it works to confirm.

**Comment by IgnorantGuru** [comment]
Yeah if you don't like that you can just make those functions do nothing, perhaps if none of the selected files have handlers.

**Comment by OmegaPhil** [comment]
k, I can see that when called via the GUI, ptk-file-menu.c:on_popup_extract_to_activate is called with menuitem, but this is NULL when its called via a keyboard shortcut. I'm going to add a boolean to indicate the validated state of the files based on this, and then have further checking in ptk_file_archiver_extract - do you agree?

**Comment by IgnorantGuru** [comment]
Not sure what you're saying is NULL.  When activated by keypress, it's run from ptk_file_menu_action() in ptk-file-menu.c, so they're very similar.  The only difference is that when the menu is shown, it only makes those menu items available if the first selected file has an archive handler.  It does this by running a high-speed, brief test (which excludes testing for empty commands, etc):

~~~~
        handlers_slist = ptk_handler_file_has_handlers(
                                    HANDLER_MODE_ARC, HANDLER_EXTRACT,
                                    file_path, mime_type, FALSE, FALSE, FALSE );
~~~~

You could simply run a similar test in ptk_file_menu_action(), inside this section:

        else if ( g_str_has_prefix( set->name, "arc_" ) )

in ptk_file_menu_action().  (data contains the mime_type of the first file, etc., like in the menu building code)

The only caveat there is Extract To via keyboard would only work if the *first* selected file is an archive (like the menu option).

I'm not too particular about it, as long as there aren't any slow tests slowing down menu or keyboard response.  ptk_handler_file_has_handlers() was optimized for speed for this purpose.

**Comment by IgnorantGuru** [comment]
Or as you say it could be tested in ptk_file_archiver_extract.  My only concern would be when activated by menu, it shouldn't do the same test twice (for performance).  Keep in mind the user may have large numbers of handlers and/or many selected files, so those tests can get slow.

**Comment by IgnorantGuru** [comment]
Your boolean idea may be cleaner than putting it in ptk_file_menu_action().  I see what you mean about menuitem being NULL.

**Comment by IgnorantGuru** [comment]
This should now be fixed in the next branch - thanks for any testing.
