### ISSUE TITLE
[request] double-clicking a folder name in tree view should expand/collapse

### ISSUE THREAD

**Issue by jmcamp** [IgnorantGuru/spacefm#542]
I'm using Spacefm v1.0.1 on Arch Linux.

When I double-click on a folder name in the tree view subfolders do not expand/collapse.

Expand/collapse on double-click is typically supported, both Pcmanfm and Thunar do.

**Comment by IgnorantGuru** [comment]
This is done in next branch, due for 1.0.4 release.
