### ISSUE TITLE
[request] line feeds in desktop item names

### ISSUE THREAD

**Issue by jmcamp** [IgnorantGuru/spacefm#543]
I'm using Spacefm v1.0.1 on Arch Linux.

I have a desktop item with Name=Mute\n(Win+M).  Spacefm recognizes the line feed, but inserts 2 new lines rather than 1.

Expected icon text:
Mute
(Win+M)

Current text:
Mute

(Win+M)

If I set "Name=Mute (Win+M)", then the icon text appears like:
Mute (Wi
   n+M)

I use a 2 line scheme for desktop icon names, the first line is the app name and the second line shows the keybinding I used in the openbox rc.xml file.

Ideally Spacefm's "Change Desktop Item Name" window would also allow adding a new line to the name by pressing the Enter key (currently the Enter key is mapped to the OK button).

**Comment by IgnorantGuru** [comment]
Thanks, this should now be fixed in next branch, due for 1.0.2 release.
