### ISSUE TITLE
[request] defer test for content type on folder loading

### ISSUE THREAD

**Issue by jmcamp** [IgnorantGuru/spacefm#544]
I'm using Spacefm v1.0.1 on Arch Linux.

I'm a Pcmanfm user who recently heard of Spacefm and have decided to give Spacefm a try.

I noticed opening directories containing many files was much, much slower on Spacefm than Pcmanfm.  This surprised me since Spacefm was originally based on Pcmanfm.

I played around with the settings and determined the main difference was an extra option in Pcmanfm v1.2.3:  "Defer test for content type on folder loading".  Apparently checking file type is very slow, and this option in Pcmanfm allows the folder to first display without indicating the file type, which is then populated by an unobtrusive background process.

To give a rough idea of the impact, the first time opening /usr/bin using Spacefm I see a blank screen for about 8 seconds on my old and slow 5400rpm hard drive.  Using Pcmanfm the file list is shown and navigable in under a second with "Defer test for content type" enabled.  If I disable "Defer test for content type" in Pcmanfm then I see a blank screen for about 8 seconds, very similar to Spacefm.

I realize Spacefm caches folders so the second time they open much faster, but I dual boot with Windows and am rebooting my PC often.

Since Spacefm is based on Pcmanfm, maybe the "Defer test for content type" logic from Pcmanfm could be merged into Spacefm without coding it all from scratch?

**Comment by HerborenInVlammen** [comment]
I have to agree. Although I do not know enough to know if your proposed solution would work.  I do agree that Spacefm is very slow at opening certain folders, and always has been.

Here are a couple of examples (note also: close Spacefm and you have to wait again should you reopen):

/usr/share/applications
/usr/bin

**Comment by IgnorantGuru** [comment]
Thanks for pointing this out - I wasn't aware that he had added that feature, and it's an interesting solution.  PCManFM is not upstream of SpaceFM though; they are now fundamentally different forks.  Not many changes there are portable.

**Comment by IgnorantGuru** [comment]
This is now included in the 'bg' branch for alpha testing - please see #582 and add any comments there - thanks.
