### ISSUE TITLE
Single or double click on a toolbar separator brings up "Change Menu Name" dialogue

### ISSUE THREAD

**Issue by HerborenInVlammen** [IgnorantGuru/spacefm#545]
Single or double click on a toolbar separator brings up a "Change Menu Name" dialogue.  Is that supposed to happen? :)

**Comment by IgnorantGuru** [comment]
Only SpaceFM allows you to name separators.  ;)

**Comment by HerborenInVlammen** [comment]
Mine are:  Larry, Curly, and Mo... :)
