### ISSUE TITLE
1.0.2 does not compile on arm due to mmintrin.h inclusion

### ISSUE THREAD

**Issue by mtasaka** [IgnorantGuru/spacefm#550]
1.0.2 does not compile on Fedora 23/22/21 armv7hl:

Direct build log:
https://kojipkgs.fedoraproject.org//work/tasks/5968/9925968/build.log

Failure part:
```
In file included from exo/exo-gdk-pixbuf-extensions.c:44:0:
/usr/lib/gcc/armv7hl-redhat-linux-gnueabi/5.1.1/include/mmintrin.h:28:2: error: #error mmintrin.h included without enabling WMMX/WMMX2 instructions (e.g. -march=iwmmxt or -march=iwmmxt2)
 #error mmintrin.h included without enabling WMMX/WMMX2 instructions (e.g. -march=iwmmxt or -march=iwmmxt2)
  ^
```

Perhaps inclusion guard 
```
#if defined(__GNUC__) && defined(__MMX__)
```
appearing on the below line is needed.

**Comment by mtasaka** [comment]
Link to the task URL
http://koji.fedoraproject.org/koji/taskinfo?taskID=9925968

**Comment by mati75** [comment]
The same issue is on Ubuntu i386 with gcc 4.6 and 4.9: https://launchpad.net/~mati75/+archive/ubuntu/spacefm-unstable/+build/7499602
https://launchpad.net/~mati75/+archive/ubuntu/spacefm-unstable/+build/7499608

Now I will check build on Debian arm.

**Comment by mati75** [comment]
Debian armhf v7:

`
/usr/lib/gcc/arm-linux-gnueabihf/4.9/include/mmintrin.h:28:2: error: #error mmintrin.h included without enabling WMMX/WMMX2 instructions (e.g. -march=iwmmxt or -march=iwmmxt2)
 #error mmintrin.h included without enabling WMMX/WMMX2 instructions (e.g. -march=iwmmxt or -march=iwmmxt2)
  ^
Makefile:1646: recipe for target 'exo/spacefm-exo-gdk-pixbuf-extensions.o' failed
make[3]: *** [exo/spacefm-exo-gdk-pixbuf-extensions.o] Error 1
make[3]: Leaving directory '/tmp/buildd/spacefm-1.0.2/debian/build-gtk2/src'
Makefile:469: recipe for target 'install-recursive' failed
make[2]: *** [install-recursive] Error 1
make[2]: Leaving directory '/tmp/buildd/spacefm-1.0.2/debian/build-gtk2'
dh_auto_install: make -j1 install DESTDIR=/tmp/buildd/spacefm-1.0.2/debian/tmp/gtk2 AM_UPDATE_INFO_DIR=no returned exit code 2
debian/rules:27: recipe for target 'doinstall-gtk2' failed
make[1]: *** [doinstall-gtk2] Error 2
make[1]: Leaving directory '/tmp/buildd/spacefm-1.0.2'
debian/rules:12: recipe for target 'binary' failed
make: *** [binary] Error 2
dpkg-buildpackage: error: fakeroot debian/rules binary gave error exit status 2
`

**Comment by IgnorantGuru** [comment]
You can see if this is fixed in the next branch.

Thanks for letting me know, but this code has been in the next branch for 3 weeks.  It would be helpful if you could tests builds sometime *before* release - that's the purpose of having the next branch, which is rolling release.  This helps make the releases more stable.

**Comment by mtasaka** [comment]
>  It would be helpful if you could test builds sometime before release

If so, I would appreciate it if you would inform some release plan, or release rc before formal release.
We don't know when you think the next branch is enough stable so it is okay for release unless there is enough information.

**Comment by IgnorantGuru** [comment]
@mtasaka I don't generally work by fixed dates, but when I make major code changes, you'll see a PLEASE TEST issue added to this tracker, sometimes using a test branch for awhile.  For example, #532 introduced the bug you found.  If you follow this repo, you should receive the issues via email, or you can watch the commits for large merges.  Things tend to get quiet for a week or so before release (a freeze with mostly just bugfixes and documentation changes).

I'm considering some changes to the release process so I'll keep this in mind.  I'm considering setting up a blog for release, testing, and pre-release announcements, so subscribing to the blog would allow for email notices. This would replace SpaceFM News page, which only shows releases and doesn't offer notifications.

Is this bug fixed for you?

**Comment by mtasaka** [comment]
> Is this bug fixed for you?
Yes, thank you. Also I appreciate spacefm development and quick response.
