### ISSUE TITLE
SpaceFM wakes up external green drives without a reason

### ISSUE THREAD

**Issue by R-a-l-f** [IgnorantGuru/spacefm#553]
Hi,

is it possible to use SpaceFM without damaging an external green drive?

I would like to turn off the automount feature, since I don't need any kind of mount feature and because it wakes up green drives without a reason.

Is there a way to disable automount or all kinds of mount at runtime or build time?

udisks2 needs to be installed on my system, hal isn't installed.

grep "enable-" configure and grep "disable-" configure didn't help.

$ pacman -Qi spacefm-gtk2
Name : spacefm-gtk2
Provides : spacefm
Depends On : gtk2  desktop-file-utils  startup-notification ffmpegthumbnailer
Optional Deps : lsof: device processes [installed]
wget: plugin download [installed]
gksu: perform as root functionality [installed]
udevil: mount as non-root user and mount networks
udisks2: mount as non-root user [installed]

The currently used option for configure by the Arch PKGBUILD
for version 1.0.2 are

build() {
  cd $_pkgname-$pkgver
  ./configure --prefix=/usr \
    --disable-pixmaps --with-gtk2
  make
}

Regards,
Ralf

**Comment by IgnorantGuru** [comment]
Please see [Devices|Settings|Automount](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#devices-settings-optical) for options.

**Comment by R-a-l-f** [comment]
Thank you,

everything is unchecked in

Devices > Settings > Show
Devices > Settings > Auto Mount
Devices > Settings > Auto Run

Everything is removed in

Devices > Settings > Device Handlers
Devices > Settings > Protocol Handlers

SpaceFM seems not to cause a spin up of the external green drive anymore.

Regards,
Ralf

**Comment by IgnorantGuru** [comment]
jfyi it's not necessary to remove the device and protocol handlers - they merely tell SpaceFM how to mount and unmount various things if you choose to or if automount is enabled.  You can restore them at any time with the All Defaults button.
