### ISSUE TITLE
tweak and/or rename gphoto handler

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#555]
I think it would be logical to add 'ptp' to whitelist of gphoto handler. Maybe even rename handler from 'gphoto' to 'ptp', since ptp protocol is what matters here, and gphoto is just an implementation.

**Comment by IgnorantGuru** [comment]
Thanks, done in 1.0.2+next.  If you modified the ghoto handler, you'll need to click the Defaults button for the new version.
