### ISSUE TITLE
Crash when clicking folders

### ISSUE THREAD

**Issue by ChowTomba** [IgnorantGuru/spacefm#559]
Systems tested on;
Ubuntu 15.04 > SpaceFM GTK2 1.0.2 > udisks2 2.1.5-1
Arch > SpaceFM GTK2 1.0.2 > udevil 0.4.4
Slackware 14.1 > SpaceFM GTK2 1.0.2 > udevil 0.4.4

I have hard time to reproduce so I can show you some output. This only happens maybe one or two times in a week, but sometimes it will happen a few times the same day. I do not know what cause this all I know is I click on a folder in my home directory and SpaceFM crashes dissappears off my desktop. I have used SpaceFM since 0.8x and I never have this crash happen until I start to use the 1.0x version.

**Comment by IgnorantGuru** [comment]
This report is vague, non-reproducilble, and matches recent troll activity on this bug tracker.  If this is a genuine report, please see the BUILD DEBUG instructions in README and add a full backtrace, as well as any output which occurs in a terminal before the crash.  Also, any settings or activity which trigger the problem - why are you seeing this on multiple systems when no one else is reporting it?  Thanks.

**Comment by ChowTomba** [comment]
I don't know about your troll activity. I also don't know about why no one else is not reporting this. But this is a real bug report, and there is a real problem, so you should not of closed this issue.

I did not mean to be vague, because I have tried everything, I do know about the debug. The problem is it's been very hard to catch this. If it was happening all the time it would certainly be easy. But when it's only happening a few times a week, I'm really having a hard time catching it.

The problem is, I have other things I need to do, so it makes it difficult to run gdb all day waiting for this to happen, so I try my best just to let you know.

**Comment by ChowTomba** [comment]
I use QupZilla and I could not edit my last reply.

I will try my best and run gdb for as long as possible and try my best to catch this, hopefully I will be able to do so, and put your mind to rest. :)
