### ISSUE TITLE
[request] -d also add icon on systray

### ISSUE THREAD

**Issue by bluebat** [IgnorantGuru/spacefm#564]
How about adding an icon on systray while using option "-d" ?

**Comment by bluebat** [comment]
and exclusive with --desktop ?

**Comment by arclance** [comment]
I personally don't want or see a reason for system tray for spacefm.
If this is added please make it possible to disable it.

**Comment by IgnorantGuru** [comment]
This would be an unlikely addition, but note that you can use a system tray utility (eg traydevice or notify-send) to add an icon or notification yourself.  You can run the utility automatically on SpaceFM start via View|Event Manager|[Startup](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#sockets-events-start) and remove it via Exit.

**Comment by bluebat** [comment]
That's OK. I will try a launcher on panel.
