### ISSUE TITLE
LilyTerm not working correctly eg unzipping file

### ISSUE THREAD

**Issue by IgnorantGuru** [IgnorantGuru/spacefm#567]
*Received [elsewhere](http://sourceforge.net/p/spacefm/discussion/general/thread/00c23efd/)*, lilyterm may not work correctly with handler and other functions.  It [appears](https://github.com/Tetralet/LilyTerm) it requires the --separate option to run each terminal in a separate instance, but SpaceFM 1.0.2 is not adding this option.

Temporary workaround:  In View|Preferences|Advanced, set the terminal to "lilyterm --separate", or use another terminal emulator such as Roxterm.

Note that lxterminal has a similar problem in <1.0.3, detailed in #552 and already corrected in next.

**Comment by IgnorantGuru** [comment]
It appears LilyTerm added a single process mode and a --separate option in [July 2008, version 0.9.4](https://github.com/Tetralet/LilyTerm/blob/master/ChangeLog#L722).  So this problem with SpaceFM + LilyTerm was introduced in LilyTerm 0.9.4.  If using LilyTerm 0.9.4 or later, add the --separate option, which SpaceFM will do automatically in SpaceFM 1.0.3 and later.

**Comment by kaqqao** [comment]
Cool, thanks for opening the ticket and even more for fixing it! (It was me reporting it on sourceforge)
