### ISSUE TITLE
ffmpegthumbnailer prevents spacefm from opening

### ISSUE THREAD

**Issue by hetraeus** [IgnorantGuru/spacefm#569]
From time to time ffmpeg does not start on my system due to codec update. The bad is that ffmpegthumbnailer crashes spacefm for this reason. Would be possible to make ffmpegthumbnailer crash gracefully while letting spacefm to start anyway?

**Comment by IgnorantGuru** [comment]
I don't think this is possible but I'm going to get another opinion.

You can add configure option --disable-video-thumbnails to build without ffmpeg support, which will prevent the crash, but then ofc you lose video thumbnailing.

**Comment by IgnorantGuru** [comment]
If this is possible, it's quite a stretch, maybe requiring a custom SIGSEGV handler, eg somewhat like [this hack](http://stackoverflow.com/questions/4136788/interrupting-a-c-function-execution-and-getting-back-to-c-caller/4147621#4147621) (thanks to @OmegaPhil for finding that one).  Or perhaps another thread approach, but the thumbnailing is already backgrounded so I would be concerned with performance on instantiating each thumbnailer in its own thread.

Nothing I plan to get into, so closing this as wontfix, but if anyone wants to come up with a solution or has input, feel free to add a comment.

fwiw, there haven't been any reports of problems with this except yours, so you might want to address the broken codecs instead - sounds sketchy.
