### ISSUE TITLE
error when compiling spacefm-1.0.3 on my slitaz

### ISSUE THREAD

**Issue by blackslitaz** [IgnorantGuru/spacefm#576]
My Configure:
	./configure \
		--prefix=/usr \
		--disable-silent-rules \
		--with-preferable-sudo="/usr/bin/ktsuss" \
		--enable-inotify \
		--enable-video-thumbnails \
		--disable-pixmaps \
		--enable-hal \
		--with-gtk2

..........
..........
SpaceFM...................................... : Version 1.0.3

Prefix....................................... : /usr
Executable................................... : /usr/bin/spacefm
Icon Dir..................................... : /usr/share/icons/hicolor/
Documentation Dir............................ : /usr/share/doc/spacefm/
Linux device support......................... : hal
Linux file change monitor support............ : inotify
64-bit Large file support.................... : yes
Additional program to switch to super user... : /usr/bin/ktsuss
GTK+ Version................................. : GTK 2
Desktop manager integration.................. : yes
Startup notification......................... : yes
Video thumbnail support...................... : yes

......
......
i486-slitaz-linux-gcc -DPACKAGE_NAME=\"spacefm\" -DPACKAGE_TARNAME=\"spacefm\" -DPACKAGE_VERSION=\"1.0.3\" -DPACKAGE_STRING=\"spacefm\ 1.0.3\" -DPACKAGE_BUGREPORT=\"\" -DPACKAGE_URL=\"\" -DPACKAGE=\"spacefm\" -DVERSION=\"1.0.3\" -DSTDC_HEADERS=1 -DHAVE_SYS_TYPES_H=1 -DHAVE_SYS_STAT_H=1 -DHAVE_STDLIB_H=1 -DHAVE_STRING_H=1 -DHAVE_MEMORY_H=1 -DHAVE_STRINGS_H=1 -DHAVE_INTTYPES_H=1 -DHAVE_STDINT_H=1 -DHAVE_UNISTD_H=1 -DHAVE_DLFCN_H=1 -DLT_OBJDIR=\".libs/\" -DSTDC_HEADERS=1 -DHAVE_STDLIB_H=1 -DHAVE_UNISTD_H=1 -DHAVE_SYS_PARAM_H=1 -DHAVE_GETPAGESIZE=1 -DHAVE_MMAP=1 -DHAVE_LIBM=1 -DHAVE_LIBX11=1 -DG_DISABLE_ASSERT=1 -DBASHPATH=\"/bin/bash\" -DHAVE_SN=1 -DHAVE_HAL=1 -DUSE_INOTIFY=1 -D_LARGEFILE64_SOURCE=1 -D_FILE_OFFSET_BITS=64 -DSUPER_USER_CHECKS=1 -DDESKTOP_INTEGRATION=1 -DHAVE_FFMPEG=1 -DHAVE_EUIDACCESS=/\*\*/ -DHAVE_EACCESS=/\*\*/ -DHAVE_STATVFS=/\*\*/ -DGETTEXT_PACKAGE=\"spacefm\" -DHAVE_LOCALE_H=1 -DHAVE_LC_MESSAGES=1 -DHAVE_BIND_TEXTDOMAIN_CODESET=1 -DHAVE_GETTEXT=1 -DHAVE_DCGETTEXT=1 -DENABLE_NLS=1 -I. -I../src/mime-type -I../src/compat -I../src/ptk -I../src/vfs -I../src/libmd5-rfc -I../src/desktop -I../src/exo -DPACKAGE_DATA_DIR=\""/usr/share/spacefm"\" -DPACKAGE_UI_DIR=\""/usr/share/spacefm/ui"\" -DPACKAGE_LOCALE_DIR=\""/usr/share/locale"\"  -Wno-deprecated-declarations -Wformat -Wformat-security -Wreturn-type -Wunused-value -D_LARGEFILE_SOURCE -D_REENTRANT -D_FILE_OFFSET_BITS=64 -DPREFERABLE_SUDO_PROG=\"/usr/bin/ktsuss\" -fstrict-aliasing -fmessage-length=0 -DDATADIR=\"/usr/share\" -DHTMLDIR=\"/usr/share/doc/spacefm\" -pthread -I/usr/include/gtk-2.0 -I/usr/lib/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libpng12 -I/usr/include/pango-1.0 -I/usr/include/harfbuzz -I/usr/include/pango-1.0 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/libxml2 -I/usr/include/freetype2 -I/usr/include/libpng12 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/startup-notification-1.0 -DDBUS_API_SUBJECT_TO_CHANGE -I/usr/include/dbus-1.0 -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/hal -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -DG_DISABLE_CAST_CHECKS -Werror-implicit-function-declaration -march=i486 -Os -pipe -fomit-frame-pointer -MT ptk/spacefm-ptk-input-dialog.o -MD -MP -MF ptk/.deps/spacefm-ptk-input-dialog.Tpo -c -o ptk/spacefm-ptk-input-dialog.o `test -f 'ptk/ptk-input-dialog.c' || echo './'`ptk/ptk-input-dialog.c
ptk/ptk-location-view.c: In function 'ptk_location_view_get_mount_point_dir':
ptk/ptk-location-view.c:738:9: error: implicit declaration of function 'vfs_volume_clean_mount_points' [-Werror=implicit-function-declaration]
         vfs_volume_clean_mount_points();
         ^
mv -f ptk/.deps/spacefm-ptk-input-dialog.Tpo ptk/.deps/spacefm-ptk-input-dialog.Po
.......
.......

sorry for my bad english
And for the complete .log:
http://pastebin.com/eSZpGJXh

**Comment by IgnorantGuru** [comment]
Thanks, should now be corrected in the next branch, due for 1.0.4 release.  (See [installer](http://ignorantguru.github.io/spacefm/#installer) for testing).
