### ISSUE TITLE
do not expect XDG_*_DIR in environment, read user-dirs.dirs

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#581]
Directories listed in "$XDG_CONFIG_HOME/user-dirs.dirs" are usually not present in the environment. Implementations need to read this config file themselves.
SpaceFM expects $XDG_TEMPLATES_DIR to be in environment and fails to read templates if the directory is localized.

**Comment by IgnorantGuru** [comment]
This should now be corrected for $XDG_TEMPLATES_DIR, assuming glib has support built-in for user-dirs.dirs - please test in next.  Note that glib >= 2.14 is required for this - using g_get_user_special_dir( G_USER_DIRECTORY_TEMPLATES ).

Afaik $XDG_TEMPLATES_DIR is the only one that wasn't read via glib.
