### ISSUE TITLE
Dependencies in Debian testing

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#583]
Hi!
libffmpegthumbnailer package in current Debian testing changed name from libffmpegthumbnailer4 to libffmpegthumbnailer4v5. Please update debian/control

**Comment by mati75** [comment]
Patch: https://gist.github.com/mati75/5b4599053034b9cf2541

**Comment by IgnorantGuru** [comment]
Thanks, this has been changed in the distros/debian/control* files distributed with SpaceFM.  No changes to the net installer were required.

Also see #571 for Debian packaging changes pending for 1.0.4 release.
