### ISSUE TITLE
Cached thumbnails are used even if they are too small

### ISSUE THREAD

**Issue by sammoth** [IgnorantGuru/spacefm#584]
Hi!

If you generate thumbnails browsing around folders in icons view and the Large Icons size set to something less than the maximum, say 128px, and then set the preference to a larger size and browse to the same folder, the cached thumbnails are reused despite being generated at the lower size and visibly pixelated when upscaled. It's possible to just delete the thumbnail cache but it would be nice to be able to change the icon size without doing this, and have any too-small cached thumbs be regenerated.

**Comment by sammoth** [comment]
I've also noticed if you have PCManFM installed too, it will put thumbnails in the "normal" size cache folder even for small icon-sized thumbs, which spacefm will then read to display much larger previews

**Comment by IgnorantGuru** [comment]
Thanks for your report.  This should now be fixed in the 'next' branch, due for 1.0.5 release.  To test this version run

    spacefm-installer --version=next

or see [net installer](http://ignorantguru.github.io/spacefm/#installer) or README.
