### ISSUE TITLE
SpaceFM doesn't start up if previous folders aren't available.

### ISSUE THREAD

**Issue by BryanFRitt** [IgnorantGuru/spacefm#585]
SpaceFM doesn't start up if previous folders aren't available.

If I close SpaceFM with a folder open that gets deleted/removed later, then try to start up SpaceFM again, SpaceFM won't start up. To start up SpaceFM, it'll need be 'killed' then started up with the '-n' or '--no-saved-tabs' option.

Better behavior: Allow startup, but with that tab with nothing in it, like the user just typed in the path while in a blank folder.

**Comment by IgnorantGuru** [comment]
Thanks for your report.  SpaceFM 1.0.0 and 1.0.1 had a bug introduced which caused a hang with inaccessible folders on startup as you describe.  This was corrected in 1.0.2.  I can't reproduce any problem in the latest.

**Comment by IgnorantGuru** [comment]
Also, if you'd like to upgrade but don't have a Debian package available, you can run the [net installer](http://ignorantguru.github.io/spacefm/#installer) to install any version.  This gets along okay with the Debian package manager, and you can always revert to the official Debian package by reinstalling it.  See the [Debian wiki](https://github.com/IgnorantGuru/spacefm/wiki/Debian) for other options.

You said elsewhere you're using 0.9.4 - that may have the startup bug as well if it was patched with some of the 1.0.0 changes.

**Comment by BryanFRitt** [comment]
Upgrading to 1.0.3 with the 'Net Installer' http://ignorantguru.github.io/spacefm/#installer fixed it.

Thanks
