### ISSUE TITLE
Shortcut to open directory in "other" panel

### ISSUE THREAD

**Issue by svenXY** [IgnorantGuru/spacefm#610]
Hi,

like with mc's alt-o, I'd like to have a shortcut to open a directory in the other (or next or previous, if other is too unspecific in spacefm).

I have successfully set the alt-o shortcut to (have to translate from  German) "right click folder -> open -> in panel -> next", but it does not do anything. I also tried with other key combinations, but to no avail

FWIW, I'm on Arch, with XFCE

Thanks,
Sven

**Comment by IgnorantGuru** [comment]
Confirmed: key shortcuts in that submenu seem to be broken in 1.0.4.

**Comment by IgnorantGuru** [comment]
This should now be fixed in the next and alpha branches, due for 1.0.5 release.
