### ISSUE TITLE
shortcut to open the same directory in the other panel

### ISSUE THREAD

**Issue by svenXY** [IgnorantGuru/spacefm#611]
when in a directory in one panel, sometimes I'd like to open the same directory in the other panel (i.e. sync the location of two panels).

Can this be done?

Thanks,
Sven

**Comment by IgnorantGuru** [comment]
Yes you can add custom commands to SpaceFM's menus and toolbars by right-clicking and selecting New|Command.  For example, to open the current directory in panel 2, use this command:

    spacefm -p 2 %d

See [command line usage](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#invocation).  You can also manipulate panels and tabs using [socket commands](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#sockets), see some [examples](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#sockets-methods).

**Comment by svenXY** [comment]
Cool, thanks for the quick help.

**Comment by svenXY** [comment]
Just in case someone finds this, here's my solution which will open the directory in the other tab (2 if 1 is focused, 1 if 2 is focused and the same for 3 and 4):

```bash
cur=$(spacefm -s get focused_panel)

case "$cur"
  in
	1) panel=2;;
	2) panel=1;;
	3) panel=4;;
	4) panel=3;;
esac

spacefm -p $panel %d

```

**Comment by IgnorantGuru** [comment]
> But this does not work if the directory contains spaces.

Just remove the quotes.  When using %d, SpaceFM will quote it automatically.  If you prefer to handle quoting yourself, use "$fm_pwd" in lieu of %d ([manual](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#designmode-props-command)).

**Comment by tbruckmaier** [comment]
In case anyone wonders how to copy the behaviour of krusader's functionality (e.g. the button on the active panel changes the active panel's tab), here is the command:

```bash
cur=$(spacefm -s get focused_panel)

case "$cur"
  in
    1) panel=2;;
    2) panel=1;;
    3) panel=4;;
    4) panel=3;;
esac

otherdir=$(spacefm -s get --panel $panel current_dir)

spacefm -s set --panel $cur --tab current_tab current_dir $otherdir
```
