### ISSUE TITLE
bookmarks sidepanel - no obvious way to reverse "show"

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [IgnorantGuru/spacefm#613]
Not sure if it is a bug or if I'm just being stupid. If the latter, consider it a feature request for all my fellow dummies.
Under the Boomarks menu there is the item "show". I clicked it and got the bookmarks sidepanel. But there is no obvious way to reverse this. Clicking again on show doesn't do it. Nothing in the View menu;  nothing in the context menu in the panel itself. Nothing shows up in a search engine, so maybe it's new or maybe it's just me.
Ubuntu 14.04 LTS, Openbox only (no DE per se), 32 bit.
Is there a way to fix this short of purging and reinstalling?

**Comment by IgnorantGuru** [comment]
It sounds like you're using an older version of SpaceFM.  In I think 1.0.0 and later, the menu item is "Show Bookmarks", and it is a checkbox item, so you can uncheck it.

In any version, you can right-click on the file list and uncheck View|Bookmarks.  Or in newer versions you can also use the main menu View|Panel N View|Bookmarks.  Any of these can be assigned a key shortcut.

**Comment by Lew-Rockwell-Fan** [comment]
Yep, 0.9.4. That's what's in the Ubuntu repo. Maybe if Lubuntu switches to Spacefm, they'll be quicker about updating, or maybe that's just the LTS version that is held at 0.9.4. Anyway, " right-click on the file list and uncheck View|Bookmarks" worked for me. Just to clarify, for anyone with a similar issue finding this with a search engine:
Right click on a file in the MAIN PANE;
Click "View" which will bring a submenu;
Click "Bookmarks" to toggle whether the bookmark pane is visible.

Thank you, IG.
This looks pretty darn cool. I think it will replace Thunar for me.

**Comment by IgnorantGuru** [comment]
I'm not sure how Ubuntu does their version updates, but if you'd like to use a newer version, the Ubuntu SpaceFM packager/maintainer also provides a [PPA](https://code.launchpad.net/~mati75/+archive/ubuntu/spacefm-unstable) for SpaceFM's [next branch](http://ignorantguru.github.io/spacefm/#branch).

There is a discussion [here](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#gui-pan) of SpaceFM's panels and panes.

Welcome - as a new user it's good to browse the manual as SpaceFM has some hidden features and depth (hidden to keep the UI brief).
