### ISSUE TITLE
Focus problem fix

### ISSUE THREAD

**Issue by williex** [IgnorantGuru/spacefm#621]
There is a focus bug that happens sometimes. Easiest way to reproduce:

- Spacefm has two or more tabs open
- The first tab is selected
- Close spacefm, start spacefm again

When pressing the left or down key the following error appears in the terminal:
(spacefm:...): Gtk-CRITICAL **: IA__gtk_widget_event: assertion 'WIDGET_REALIZED_FOR_EVENT (widget, event)' failed

This can be fixed by changing the function on_file_browser_after_chdir.

Removing the call to gtk_widget_grab_focus In src/main-window.c seems to fix the problem because the focus call is redundant. However, I'm not sure this is the best fix, maybe IgnorantGuru can comment on this.

**Comment by OmegaPhil** [comment]
This sounds like the problem I was fighting with IG a while ago - in alpha this line is commented out, the problem then doesn't happen with GTK2 or GTK3.

**Comment by williex** [comment]
Ha, you're right. I only check the master branch and tickets but didn't find anything. Good to have confirmation.
