### ISSUE TITLE
mtp update

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#624]
Please add `mtab_fs=fuse.Locked(fs.rootNode)` to mtp handler whitelist. Apparently, this is the case for newer versions of go-mtpfs.

Perhaps, it may be logical to make one umount handler for all fuse filesystems which would do `fusermount -u`

**Comment by IgnorantGuru** [comment]
Also noting that this use of mktemp is probably not busybox compatible due to the trailing ".tmp":

    mktemp --tmpdir spacefm-go-mtpfs-output-XXXXXXXX.tmp

**Comment by IgnorantGuru** [comment]
1.0.6 fixes the tmpdir for busybox.  The new mtab was not used (is not necessarily specific to mtp), but 1.0.6 includes a general 'fuse unmount' handler.
