### ISSUE TITLE
No thumbnails with mounted protocols

### ISSUE THREAD

**Issue by 4r1y4n** [IgnorantGuru/spacefm#630]
When you browse a protocol mounted filesystem (e.g. sshfs ) , videos and images thumbnail feature doesn't work and no thumbnail is generated at all.  
I'm using SpaceFM 1.0.5 on Lubuntu 14.04:

```
spacefm 1.0.5
GTK2 UDEV INOTIFY DESKTOP SNOTIFY
```

**Comment by Vladimir-csp** [comment]
IIRC, thumbnails are disabled for filesystems in change detection blacklist, see menu:
Device | Settings | Change detection

**Comment by mariusvam** [comment]
ㄘ
Sent via BlackBerry from T-Mobile

-----Original Message-----
