### ISSUE TITLE
Icon oddness in downright corner

### ISSUE THREAD

**Issue by biopsin** [IgnorantGuru/spacefm#635]
![2016-04-05--1459841736_599x148_scrot](https://cloud.githubusercontent.com/assets/7681285/14274775/9ab628e0-fb13-11e5-9bf1-c400c561e689.png)
It doesn't seem to have any function..

**Comment by IgnorantGuru** [comment]
The icon at the right of each panel's status bar is used to show which panel has focus when multiple panels are visible, [documented here](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#gui-pan-foc).  These icons are also shown in the Panel Bar at the top.  You can customize the icon for a panel by right-clicking on its status bar and selecting Icon.

From your screenshot showing a red 'X' broken icon, it looks like you don't have the stock GTK icons installed (that icon is "gtk-yes" by default).

**Comment by biopsin** [comment]
Thank u IgnorantGuru - User error, I change icon long ago and forgot.
