### ISSUE TITLE
slow loading times for huge directories

### ISSUE THREAD

**Issue by hasufell** [IgnorantGuru/spacefm#637]
I have a directory:
```
ls -la /var/log/paludis | wc -l
41774
# du -sh /var/log/paludis
8,2G     /var/log/paludis
```

It consists of text files only with different file endings and no hidden files. It takes up to __5 minutes__ to load in spacefm. The problem cannot be just the huge amount of files read via the directory stream, because just listing the files in other implementations (including GTK visualization) is considerably faster and finishes in __5-10 seconds__. So there must be something that is run for every file and which takes a lot of time (showing thumbnails maybe?).

I haven't done proper profiling yet to figure out which function is causing this. But the runtime tests were done both with cold cache.

**Comment by IgnorantGuru** [comment]
Determination of a file's MIME type may require opening the file, which is what mostly slows down dir load.  You can compare 1.0.5 or next to the behavior of alpha per #582.

**Comment by stewie** [comment]
When "show thumbnails" is set false in preferences, does spacefm skip the mime-sniffing step? 
I hope it would. In that case, mime never needs to be checked unless context menu is opened for a file
(to support open, openWith)

**Comment by IgnorantGuru** [comment]
SpaceFM always determines the MIME type of each file, as this determines the icon shown (and the optional Type column).  alpha shows the directory first and loads the MIME types and icons in the background, unless you activate or click a file in which case it gets that file's type immediately to show the menu, etc.
