### ISSUE TITLE
[Ubuntu] Main menu bar menus are empty

### ISSUE THREAD

**Issue by kalamalka** [IgnorantGuru/spacefm#643]
I recently upgraded from SpaceFm 0.9.4 to 1.0.1 using the [net installer](https://ignorantguru.github.io/spacefm/#installer), however there seems to be a major issue upon launch. I have noticed that all of the file menu options are missing and the only items that show in any menu say 'activate' on all the _file_, _view_, _devices_, _Bookmarks_, _Pluggins_ etc..

I ensured the themes were not conflicting by using default themes (no errors in console)
I also tried:

```
killall spacefm
spacefm -c /tmp/spacefm-test
``` 

this produced the same problems. 

the output of 'spacefm --version' is GTK3 UDEV INOTIFY DESKTOP SNOTIFY
the output of dpkg -s libgtk2.0-0|grep '^Version' is  2.24.23-0ubuntu1.4
the output of dpkg -s libgtk-3-0|grep '^Version' is 3.10.8-0ubuntu1.6
Running Ubuntu 14.04 64 bit

**Comment by IgnorantGuru** [comment]
Please always upgrade to the latest version, currently 1.0.5, or 'next'.  Also, your GTK3 version is very out of date and likely buggy.

Beyond this, SpaceFM often doesn't work well with panel apps that steal the GTK menus (see #518 #49 for examples), including Ubuntu's Unity.  This is because such apps prevent direct click detection on the menus.  You can try using Alt+F to show them via keyboard, stop using the panel app which is interfering with SpaceFM, or set the panel app to ignore SpaceFM.

I'll leave this open to collect info but this is a likely a problem which will have to be fixed by providing SpaceFM with a stable GTK3 environment without interference from other apps.

**Comment by IgnorantGuru** [comment]
Also, you might avoid this problem by building a GTK2 version of SpaceFM (add --with-gtk2 at the net installer's option prompt).  That may be why your 0.9.4 install didn't have the same problem - it may have been GTK2.  And as I said, use of 1.0.5 or 'next' may also help.

Also note there is an [Ubuntu PPA](https://launchpad.net/~mati75/+archive/ubuntu/spacefm) maintained by the official packager, obviating the need for net installer.  If you use the PPA to upgrade to 1.0.5 and the problem persists, you might file a bug there and see if the packager is aware of a solution for Ubuntu.

**Comment by kalamalka** [comment]
What a complete nightmare trying to upgrade GTK3. There is just a total wormhole of dependencies I can not possibly install without totally breaking my system. I cant possibly comprehend how anyone could make this work at all. 

Im going to try to install the 1.0.5 and hopefully it works out. Keep you posted.

**Comment by IgnorantGuru** [comment]
> What a complete nightmare trying to upgrade GTK3.

Usually best to use the version that your distro has packaged in its routine updates.  I was just pointing out that your version of Ubuntu is using a fairly old and buggy version of GTK3, so this could be contributing to the problem.  However, I don't recommend upgrading it beyond updating Ubuntu.

> How would I go about installing 1.0.5 with --with-gtk2 . ?

    spacefm-installer --version=1.0.5 --with-gtk2 --prefix=/usr

**Comment by kalamalka** [comment]
thank you . I love this app so much. It's what makes me want to use Ubuntu. Its really amazing with the new features too. 

BRAVO

**Comment by IgnorantGuru** [comment]
Thanks.  So upgrading Ubuntu solved the problem for both GTK2 and GTK3 builds of SpaceFM (meaning this issue can be closed), or just GTK2 (meaning this issue should be left open to track the GTK3 problem)?

**Comment by kalamalka** [comment]
I think the version featured in synpatic had gtk3 upgrade, but I'm not sure. maybe leave it open

**Comment by kalamalka** [comment]
this totally destroyed my system with the GTK3. Not sure how I'm even going to fix this. Unity is taolly screwed up now.

**Comment by IgnorantGuru** [comment]
This problem with the main menu bars empty on Ubuntu may be corrected or affected by the change in alpha detailed [here](https://github.com/IgnorantGuru/spacefm/issues/518#issuecomment-366786798).
