### ISSUE TITLE
User icons not loaded for .desktop files

### ISSUE THREAD

**Issue by Vladimir-csp** [IgnorantGuru/spacefm#647]
SpaceFM 1.0.5 on Debian jessie.
Desktop entry generated by wine has:

```
Icon=F71B_Cons.0
```

This icon can be found in following paths:

```
.local/share/icons/hicolor/48x48/apps/F71B_Cons.0.png
.local/share/icons/hicolor/32x32/apps/F71B_Cons.0.png
.local/share/icons/hicolor/16x16/apps/F71B_Cons.0.png
```

But .desktop files are show with generic icons. 'hicolor' is one of the fallback themes, so it should be probed for icons, including on user-level paths.

**Comment by IgnorantGuru** [comment]
Teklad's fix for this has been merged into next and alpha, due for 1.0.6 release.  Does this correct the issue?
