### ISSUE TITLE
[Feature Request] Default Drag Action: None

### ISSUE THREAD

**Issue by 0ion9** [IgnorantGuru/spacefm#651]
I use a graphics tablet as my sole input device. That means it's very easy to start a drag. I have never dragged a file _intentionally_ to move or copy it, but nonetheless, on many occasions, SpaceFM has decided that that was what I wanted it to do, and moved my directories around undesirably.

It would be nice to be able to stop this behaviour altogether, hence my suggestion for an additional 'Default Drag Action: None'

**Comment by IgnorantGuru** [comment]
A 'Disabled' mode has been added to Default Drag Action in the alpha branch (see net installer for testing this branch).  This should make dragging in the file list and dir tree do nothing.

Note that bookmarks can still be dragged to reorder them, and tabs can still be dragged to reposition them.  These are probably less likely to be done accidentally?
