### ISSUE TITLE
Segfault when dragging folder or file on desktop

### ISSUE THREAD

**Issue by fiszts** [IgnorantGuru/spacefm#654]
When I'm trying to drag any file or folder from the file manager (have tried spacefm, pcmanfm, thunar) to spacefm desktop right bottom corner (custom arranged) I got segfault every time.

(Debian, spacefm 1.0.5 gtk2)

**Comment by IgnorantGuru** [comment]
@Teklad's fix for this has been merged into next and alpha, due for 1.0.6 release.
