### ISSUE TITLE
Any change made to bookmarks is implememted in root user bookmarks, and vice versa.

### ISSUE THREAD

**Issue by HerborenInVlammen** [IgnorantGuru/spacefm#655]
I  have no idea how this occurred, but if I change, add, remove etc. a bookmark, or any configuration changes in SpaceFM, the same change is also displayed in the root account bookmarks, and vice versa.  However, if I view the actual bookmark files in a text editor they are different as they should be.

I can delete the spacefm folder in /HOME./config, and open a root spacefm window and I will get a vanilla root spacefm config even though the root user spacefm config is in the /root/.config/ folder when the root window is opened.  Also vice versa.

I remember reading that someone else had this issue a year or so ago, but I cannot find it in the issues, and I spent an hour looking.  I have rebooted, shutdown, deleted configs on all user accouts, and this still happens.  I have uninstalled and reinstalled to no avail.

**Comment by HerborenInVlammen** [comment]
OK, I fixed this by manually removing all evidence of SpaceFm (except for icons existing prior to install), and then reinstalling via the latest source (the repos also worked).  I have zero idea why this happened.  

NOTE: In the course of the above manual scrubbing, I found that neither apt (when I tried the repos version), nor your "spacefm-install --uninstall" script removed the spacefm exec, spacefm-auth script, and of course the installer script from /usr/local/bin.  This results in still being able to run Spacefm after the uninstall.  That has got to be a bug :)  

Note that this happened on Xenial Xubuntu.

**Comment by IgnorantGuru** [comment]
Generally the problem here is how the root instance of SpaceFM is run.  eg If it's run in an environment where HOME is set to the user's home instead of to root's home, then the root instance will use the user's SpaceFM configuration directory.  This isn't a good idea, so set HOME (or other appropriate variable such as XDG_CONFIG_DIR) to /root or /root/.config, etc.

I don't see why the installer didn't remove the executable but I've made a note to look.

**Comment by HerborenInVlammen** [comment]
Well, it was not done on purpose :)  Damn.  It was a bugger.

I can reproduce the issue at will by making the same mistake I made ...

1) Use deja-dup to /manually/ restore spacefm configuration files WHILE
forgetting that I had a root spacefm window open on another workspace. 
If the root config is restored while a root window is open the issue
occurs and the config ends up having user permissions mixed with root
permission.

I have got to say that it is one hell of a bugger to get rid of.  Even
removing all configs from all users does not fix it.  So, further
exploration showed that root permissions were applied to SOME but not
all of the user config files, and vice-versa as well as the actual root
folder of the config folders  (~./config/spacefm etc.) and not just its
contents.

While it is my mistake, IMO, this sort of thing should be preventable
with proper permission checking the OS ... i,e,, just because one has
invoked root privileges does not mean no warnings are ever necessary. 
Even the best of us can stay up way too late trying to configure a new
OS (such as I was doing) and make dumb mistakes. 

Overwriting root permissions with user permissions (and vice versa)
needs to have a warning even if one is root ... And this should not be
the responsibility of app devs... it should be in the OS.

I mean if you can have "permission denied" messages out the arse for
anything else ... then why not for when you can do real damage...?

I rant ....


Thanks for the input :)
