### ISSUE TITLE
SpaceFM doesn't refresh mounted ZFS directories

### ISSUE THREAD

**Issue by nsheff** [IgnorantGuru/spacefm#656]
spacefm stops refreshing ZFS mounted directories after a few hours.

I mount a ZFS directory (served by FreeNAS), use spacefm to navigate to this directory. Everything displays fine. Now make a change (outside spacefm) in the directory. As expected, this change is not reflected in spaceFM (it requires a refresh). Press refresh. The screen blinks, new files are displayed. This is the expected behavior.

Now, wait a few hours. Do the same thing... Make a change outside spacefm, Press refresh, nothing happens. No blink, no update. Try on a local directory. Press refresh: the screen blinks; list refreshes and new files are displayed.

New windows have the same behavior; they don't work on ZFS directories. Restart spacefm completely: Now it works for a couple of hours.

The strange thing is that it seems spacefm isn't even __trying__ to refresh it, because the screen doesn't blink. It just does nothing.

**Comment by IgnorantGuru** [comment]
You might try alpha (see #582) as Refresh has been redesigned, to see if the problem still exists.  The older method won't refresh if multiple tabs are open to the same directory, for example.

**Comment by nsheff** [comment]
I believe the symptoms were just cause by multiple tabs being open to the same directory. The time delay was just because over time, I was more likely to open another spacefm window. Now that I'm aware of this quirk, the problem has disappeared. Thanks!
