### ISSUE TITLE
Recomendation for handling deleted directories that are open in a tab

### ISSUE THREAD

**Issue by maximstewart** [IgnorantGuru/spacefm#661]
I would like to see an option where if a directory is closed but open in a tab that the tab move up relative to the deleted directory. When doing work on my file system it gets inconvenient to have to re-open a tab to the next desired location because I deleted a folder the tab is looking at and said tab closes. Since paths have '/' in them it should be easy enough to query which next level to move up to. If it goes past the user dir then the tab should be killed.

**Comment by ghost** [comment]
Closed since this isn't being maintained by @IgnorantGuru
