### ISSUE TITLE
How to prevent leftover task after starting gui program in the background

### ISSUE THREAD

**Issue by Ryan1729** [IgnorantGuru/spacefm#662]
I have created a command with the following script:
```bash
#!/bin/bash

git-gui &

exit 0
```

This opens `git-gui` opening the git repo in the current directory if ther is one, as expected, but it leaves a task in the task manager that displays 100% completed. `git-gui` stays open if the task is stopped, but it is annoying to have to stop it. Is there a way to start a GUI program from a command/plugin without leaving a task behind?

**Comment by ncmprhnsbl** [comment]
rightclick your tool/menuitem> Properties> Options(tab)> uncheck 'Run as Task'

btw something as simple as this can be set up as a 'Command" instead of a script..
be sure to read the excellent documentation in spacefm help ;)

**Comment by Ryan1729** [comment]
I changed it into a Command and unchecked "Run as Task" and it works as expected now. Thanks!

I had looked at part of the documentation and I had assumed that something like that would have been mentioned in the Plugins > Creation And Files  section, but it wasn't. It might be worth linking to the description of the Design Mode > Properties section from there?
