### ISSUE TITLE
Editing custom commands (that are grayed out)

### ISSUE THREAD

**Issue by Nilbmar** [IgnorantGuru/spacefm#663]
I made a mistake in the Context section of a custom command I was writing to work with a file. Because of that, it was grayed out in any possible context.

With the command grayed out, you can't right-click on it to edit and fix the context.

**My solution** (in case anyone with the same issue sees this)
1. I deleted `~/.config/spacefm/session-last` and `~/.config/spacefm-prior`.
2. Then edited `~/.config/spacefm/session`
3. Rebooted before opening SpaceFM back up.
4. I had to find the command by searching for what I had named it, and checking what it's `cstm-#######-next=` and `cstm-*******-prev=` lines for menu items above and below it.
5. I edited the line that starts with `cstm-#######-cxt=` to one I copied from another command I knew I could see. However, I suspect you can just delete this line to see it no matter the context.

Having a dedicated tool that will list all custom commands, and allow you to start the same Edit function as the right-click menu, would be very useful in fixing this sort of problem.

**Comment by IgnorantGuru** [comment]
Please see [Ignore Context](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#designmode-props-ignorecontext).
