### ISSUE TITLE
Set --reuse-tab as default behavior?

### ISSUE THREAD

**Issue by LindyBalboa** [IgnorantGuru/spacefm#669]
Is there any way to do this? I don't see it in the preferences menu and see no way to do this with the config file. At the moment I am using Kupfer as a launcher, which doesn't really support appending runtime options and I don't feel like adding an extra script. 

Thanks team!

**Comment by IgnorantGuru** [comment]
This is controlled by the method you use to run SpaceFM.  eg you can copy SpaceFM's .desktop file from /usr/share/applications to ~/.local/share/applications and change the command it uses to run spacefm (will affect starting it from a menu), use a shell alias, script, keyboard shortcut in your window manager, etc.
