### ISSUE TITLE
double free / corruption crash

### ISSUE THREAD

**Issue by jmcamp** [IgnorantGuru/spacefm#673]
I'm using Spacefm alpha on Arch Linux with Gtk 3.22.3 and the default Adwaita theme.

Spacefm occasionally crashes.  It happens randomly, I haven't yet been able to reproduce it consistently.

[Attached](https://github.com/IgnorantGuru/spacefm/files/588110/spacefm.txt) is what is written to the console upon a crash.

**Comment by IgnorantGuru** [comment]
Likely caused by one of the unresolved thread timing issues in alpha, which affect some systems more than others.

**Comment by IgnorantGuru** [comment]
All known crashes in alpha, including those described by above backtraces, should be corrected in alpha as of f91c4b4  If anyone does still see any crash or GTK warnings from alpha, please report it again in this issue or elsewhere.

To obtain a complete backtrace, please see the BUILD DEBUG instructions in the [updated README](https://raw.githubusercontent.com/IgnorantGuru/spacefm/1805a151af27a0d4c1f03247e9751b0813564d66/README).
