### ISSUE TITLE
Drag to select multiple file/folder

### ISSUE THREAD

**Issue by thanhngvpt** [IgnorantGuru/spacefm#674]
Hi Author.
Can i use mouse to select multiple file/folder to copy or moving?
Thanks

**Comment by HerborenInVlammen** [comment]
Yes you can.  However, there is a GTK bug that causes groups of selected files or folders to become "unselected" unless one holds down the CTRL key while doing it.  

I have experienced this bug in other GTK apps, but  very rarely.  In SpaceFM it occurs every time.

Just get used to holding down the CTRL key

Not sure if that answers your question as it was a little short on details :)

**Comment by thanhngvpt** [comment]
it work well, many thanks @HerborenInVlammen
