### ISSUE TITLE
Unable to build on Gentoo - vfs/vfs-volume-nohal.c:1096:29: error: called object ‘major’ is not a function or function pointer

### ISSUE THREAD

**Issue by OmegaPhil** [IgnorantGuru/spacefm#678]
[zlg/sporkbox has relayed a Gentoo bug reported by Toralf Förster](https://bugs.gentoo.org/show_bug.cgi?id=603000):

```
vfs/vfs-volume-nohal.c: In function ‘info_mount_points’:
vfs/vfs-volume-nohal.c:1096:29: error: called object ‘major’ is not a function or function pointer
                     major = major( statbuf.st_rdev );
                             ^
vfs/vfs-volume-nohal.c:1047:13: note: declared here
```

Even though its not in caps, this is a macro, and [glibc no longer includes them by default](https://sourceware.org/ml/libc-alpha/2015-11/msg00253.html).

A patch for adding the missing include is [here](https://603000.bugs.gentoo.org/attachment.cgi?id=456706).

**Comment by OmegaPhil** [comment]
sporkbox: I was reading into this, and [it feels like a new macro should be added to configure.ac rather than patching the one file: AC_HEADER_MAJOR](https://sourceware.org/ml/libc-alpha/2015-11/msg00256.html) ([thread start](https://sourceware.org/ml/libc-alpha/2015-11/msg00253.html)) - since this will allow the 'major' macro to be used anywhere in the source without remembering to use a special include.

Does this solve the problem for you? Currently the change hasn't reached Devuan Testing that I'm using.

**Comment by mati75** [comment]
On unstable debian is build well. On the same upstream glibc version.

**Comment by OmegaPhil** [comment]
Interesting, but the problem being presented does look legit though? So perhaps its a Gentoo issue for now?

**Comment by mati75** [comment]
In description of gentoo bug also is info about the same problem on udevil package. In Debian I pushed fix for that more than year ago.

**Comment by OmegaPhil** [comment]
Ah right, you're referring to device-info-sys-stat.patch - can you comment on whether AC_HEADER_MAJOR is a better idea or not?

I now have commit access to udevil so I can also get this in there (plus anything else missing as long as I understand what its doing).

**Comment by OmegaPhil** [comment]
Have updated the initial post as per zlg's request (he doesn't have a Github account) - I'll get this incorporated in SpaceFM next now.
