### ISSUE TITLE
x265 Incompatibility

### ISSUE THREAD

**Issue by dnut** [IgnorantGuru/spacefm#680]
The latest version of x265 provides libx265.so.102, not libx265.so.95. SpaceFM won't run without libx265.so.95 being present in the system, even if thumbnails are disabled. For testing, I symlinked 102 to 95 and SpaceFM runs fine, except it crashes when I open a directory with videos in it (only if thumbnails are enabled).

Launch error:
```
spacefm: error while loading shared libraries: libx265.so.95: cannot open shared object file: No such file or directory
```

Crash error:
```
spacefm: symbol lookup error: /usr/lib/libavcodec.so.57: undefined symbol: x265_api_get_95
```

**Comment by mati75** [comment]
This is ffmpegthumbnailer problem, not spacefm.

**Comment by dnut** [comment]
Even if it is an ffmpegthumbnailer problem, this behavior seems like poor exception handling by SpaceFM.

**Comment by mati75** [comment]
Disagree, ffmpegthumbnailer should be rebuild with newest x265 and it solved the problem.

Which distro do you have?

**Comment by dnut** [comment]
I use Arch, and the ffmpegthumbnailer in the repos is out of date. I flagged it though so the next version has been brought into testing. I'll see how that works when I get the time.

When an entire application fails to launch because of an issue in a dependency used for an optional and unnecessary feature (even when that feature is disabled), that calls into question the robustness of the underlying code. The ease with which the dependency can be fixed has nothing to do with it.

**Comment by ncmprhnsbl** [comment]
could not reproduce this..  (before ffmpegthumbnailer-2.2.0-1 update)
however, i am using a gtk2 build of spacefm, so i suspect this crashing behavoiur is peculiar to the gtk3 build..

**Comment by IgnorantGuru** [comment]
I doubt SpaceFM can handle this anymore gracefully than it is.  It is printing the cause of the error.  A library is not merely an option in the program, it is part of the running code, so if it fails, the program stops.  As others pointed out, this looks like a ffmpegthumbnailer package manager issue on the system.

SpaceFM can also be built without video thumbnail support, which takes the ffmpegthumbnailer library out completely.  For such a custom build, you can use SpaceFM's net installer or see README.
