### ISSUE TITLE
Dialog: if --label has Pango markup, --click gives sintax error

### ISSUE THREAD

**Issue by paoloschi** [IgnorantGuru/spacefm#681]
this is the example for `--click` from the spacefm manual with a Pango addiction:

    spacefm -g --label "~<b>Click HERE</b>" \
               --list 111 222 333 -- \
               --input \
               --click bash -c 'echo %v >&2'

clicking on label, the bash command complains syntax error at line 0

**Comment by IgnorantGuru** [comment]
%v needs to be double-quoted in this case, as quoting is not implied in the case of these substitution variables; it is a raw substitution.  (This is seen in other examples in the manual.)  Probably should be quoted in the manual for this case too.

Works like this:

~~~~
spacefm -g --label "~<b>Click HERE</b>" \
           --list 111 222 333 -- \
           --input \
           --click bash -c 'echo "%v" >&2'
~~~~

**Comment by paoloschi** [comment]
Thanks for the exhaustive explanation!
and, above all, I am happy for this sign of continuity of the project (..) 
As interesting as it may be, personally I continue to develop scripts with SpaceFM v1.0.5 Dialog in Void Linux practically on every day basis !
the utility that comes with it is fantastic.........  :-)
