### ISSUE TITLE
SpaceFm wont open with  Unable to initialize inotify file change monitor after several days

### ISSUE THREAD

**Issue by NebrMom** [IgnorantGuru/spacefm#685]
After using Space FM for several days I get an error message and it won't open and gives an error message 
 Error: Unable to initialize inotify file change monitor.

Do you have an inotify-capable kernel?

Then I can not use SpaceFM without rebooting. Then it works again for awhile

**Comment by Vladimir-csp** [comment]
Is inotify working after the error?
try running this:
```
touch /tmp/testfile
inotifywait -e open /tmp/testfile && echo SUCCESS &
cat /tmp/testfile
```

**Comment by NebrMom** [comment]
I just restarted the system so it currently doesn't generate 
the error. I will try this the next time it happens. I would 
love to solve this so I didn't have to fall back to PCManFM 
or restart the system to use SpaceFM
               Thank You
                Linda

**Comment by NebrMom** [comment]
It is doing it again so I ran your commands and get
Couldn't initialize inotify.  Are you running Linux 2.6.13 or later, and was the
CONFIG_INOTIFY option enabled when your kernel was compiled?  If so, 
something mysterious has gone wrong.  Please e-mail radu.voicilas@gmail.com
 and mention that you saw this message.

inotify-tools is installed

**Comment by NebrMom** [comment]
Don't know if this helps but now restarted the system and everything works now get this result from your command
$ Setting up watches.
Watches established.
cat /tmp/testfile
/tmp/testfile OPEN 
$ SUCCESS

**Comment by Vladimir-csp** [comment]
So inotify becomes busted sytem-wide.

Here a similar error was produced when there were too many inotify processes running: http://stackoverflow.com/questions/33286033/inotifywait-running-daemon-mode-giving-error-couldnt-initialize-inotify

So maybe something on your system exhausts inotify resources. Which may or may not be spacefm.
BTW, limits are represented in `/proc/sys/fs/inotify/max_*`

I do not know how to check which processes have active inotify requests.

**Comment by NebrMom** [comment]
Changed from the spacefm-gtk3 to spacefm and have not had the error for a few weeks so I think it has solved the problem.

**Comment by IgnorantGuru** [comment]
Just noting that it is unlikely that the GTK version affected this, more likely was a system issue, probably not caused by SpaceFM but affecting it.
