### ISSUE TITLE
Big size in rename windows

### ISSUE THREAD

**Issue by Dikakus** [IgnorantGuru/spacefm#686]
Hi,

I'm using spacefm with two monitors (extended desktop). Every time I rename a file (F2) the renaming window grows and grows, taking up the whole desktop and I can't resize it. It's very annoying because it covers the others windows and I have to switch constantly between them.

Thank you.

**Comment by HerborenInVlammen** [comment]
Hi Dikakus:
Would you mind posting what distro, GTK version, and theme you are using?  I too use the extended desktop on Xubuntu Xenial, without any issues.  

Chances are it is a theme/GTK issue.  The place to start is there anyway.

**Comment by Dikakus** [comment]
I'm very sorry. I had to have post this information before.

I'm connecting to a Debian Jessie 4.6.0-0.bpo.1-686-pae in a old machine through ssh and  X11 forwarding. The client machine is a laptop with Windows 7 and Xming 6.9.0.31 Server.

GTK installed versions  2.24.25-3+deb8u1 and 3.14.5-1+deb8u1. 
LXDE 6 with Clearlooks theme.

SpaceFM version 1.0.5.

**Comment by Bfgeshka** [comment]
Cannot reproduce.

Two different monitors setup, Gentoo, latest commit of spacefm-next, x11-libs/gtk+-2.24.31-r1, x11-base/xorg-server-1.19.2.

**Comment by HerborenInVlammen** [comment]
I can almost gaurentee you the issue is the Clearlooks theme.  SpaceFM
locks up on my system using that theme (See issue #677 last comment done
yesterday). 

Also, try SpaceFM 106, as several issues were fixed.

**Comment by Dikakus** [comment]
Hi! Thank you very much @HerborenInVlammen !

I tried changing the Clearlooks theme. I'm using Crux now. I've been using it for a couple of days and it seems working perfectly: the renaming window doesn't grow anymore, and I can resize it in addtion.

Best regards.

**Comment by HerborenInVlammen** [comment]
Glad to hear it!  Note that Clearlooks causes issues with other programs
for me as well.  I do not think it is a SpaceFM issue per see.
