### ISSUE TITLE
NOTICE: Project Status Update and A Fork

### ISSUE THREAD

**Issue by IgnorantGuru** [IgnorantGuru/spacefm#687]
Hello to all,

This repo of SpaceFM is no longer in active development (you're still welcome to use this issue tracker).  I just want to bring attention to a fork which is being worked on by @Teklad called [spacefm-ng](https://github.com/Teklad/spacefm-ng).  He has forked from SpaceFM 1.0.5+next, and has fixed some of the bugs reported here.  He has also worked on documentation, etc., and has merged some work from others.  I was just made aware of this fork, so I haven't reviewed it in detail, but according to @OmegaPhil it's the strongest fork going.

Also, if you would like to run [alpha](https://github.com/IgnorantGuru/spacefm/issues/582) but with his bugfixes and changes, you might be able to merge his work into alpha fairly easily, as I mentioned in [spacefm-ng issue 6](https://github.com/Teklad/spacefm-ng/issues/6).  alpha usually runs quite well and has some nice features and improvements - quite a bit of work went into it, but it didn't quite make it to release.

Translators:  Please note that SpaceFM's [Transifex server](https://www.transifex.com/ignorantguru/spacefm/) is populated with files from alpha (I just pulled the updates into alpha today - thanks for the work!)    These are missing many strings used in next, so these files won't work well with next (or with Teklad's master branch).  However, it is possible to merge po files - there are tools to do that.  I also discuss this in [spacefm-ng issue 6](https://github.com/Teklad/spacefm-ng/issues/6).

<del>Finally, please note that my old email address, ignorantguru@gmx.com, is effectively gone, yet it doesn't seem to be bouncing mail yet, it just vanishes.  My new openmailbox email address may be obtained from [my updated PGP key](https://pgp.mit.edu/pks/lookup?search=0x01937621%20&op=index).</del>  [Update 2018-01-22: ALL the email addresses on my PGP key are currently defunct - do not use - but I can usually be reached here on Github.]

Best wishes,
IG

**Comment by HerborenInVlammen** [comment]
I just wanted to thank you IG for all the work and sweat you put into this project.  I know it (and we) must have made your hair fall out at times, but from this end, I cannot imagine using another file manager.  Period.

Good luck to you in all you do!

Cheers!

**Comment by IgnorantGuru** [comment]
Thank you.  You guys definitely wore me out, but I really enjoyed developing SpaceFM.

SpaceFM isn't going away.  It has undergone years of attention to detail, both from myself and from contributors, including users.  It's a nice tool with some genuine quality.  I'm still using it everyday.

I always encourage new and even experienced users to browse through the user's manual and discover all SpaceFM can do.

If you are interested in further development in the project, there are always bugs remaining to be fixed, and GTK3 development will especially need attention if it is to be stable on that bed of sand.  Yet even with GTK3, with a non-broken theme it seems to be running well in general.  You might have to put up with a few glitches there if it's not maintained relative to GTK3's changes.

If you are interested in SpaceFM running without problems, I recommend sticking to GTK2 with a nice light theme.  And do yourself a favor and install udevil, so you are no longer subject to udisks, policykit, etc.

SpaceFM was always a prototype so it was never intended for this codebase to be developed extensively beyond its current scope.  It was a place to try some ideas, while also achieving a level of excellence in the engineering (I like a real tool, simply put, not a toy.)  Beyond bugfixing it and some feature extensions, I would expect a rewrite would be more feasible than building extensively on this code.  But that's a lot of work, writing something like this from the ground up!  In that sense, this codebase is valuable, as independent and stabilized as it is, even as a prototype.

As far as how it's currently running, there have always been occasional reports of SpaceFM running horrible for someone.  I don't doubt it, it's just the nature of developing on such a changing and varied OS, libraries, etc.  Yet for the most part, SpaceFM is a remarkably reliable piece of software to this day, developed to high standards.  It doesn't need much attention at this point to continue being what it is.  Of course, software is never 'done'.

My reasons for backing off the project are selfish and complex - it's a torrid love affair - but I still think SpaceFM is a cool file manager.  No doubts about that, and it has some genuine fans.  It was exciting how it evolved, and it was a pleasure to work on (certain GTK issues not withstanding).  I have pages of ideas on how such a UI could evolve.  But of course there is quite a distance between an idea and a capable, reliable tool.

**Comment by Teklad** [comment]
This is more or less along my lines of thinking.  Maintaining SpaceFM as-is for the most part and rewriting elsewhere implementing the various features SpaceFM contains.  That's the long-term intention, at least.  

If I remember correctly this was originally "PCManFM-mod"?  I remember poking at it back then and thinking how neat the idea behind it was, but at some point I had forgotten about it due to not using a file manager for an extensive period of time (I went through one of those GUIs are evil stages).

Anyhow, bug patches and new features are always welcome as a PR for SpaceFM.  I'll try to be as responsive as possible regarding immediate issues, crashing and undefined behavior type stuff, anyways.

On a side note:  Everyone is selfish in their own right, so nobody blames you there, IG. :P

**Comment by IgnorantGuru** [comment]
Yeah you can read the short [development history](http://ignorantguru.github.io/spacefm/spacefm-manual-next-en.html#introduction-history) for background, plus a [SpaceFM: How and Why?](https://igurublog.wordpress.com/2012/01/14/spacefm-how-and-why/) post I wrote shortly after SpaceFM's initial release (feature info there is somewhat dated and inaccurate, eg keyboard use of Design Mode was added long ago).  PCManFM-Mod was just a few hacks applied to bugfix and extend legacy PCManFM.  When I created SpaceFM, I tore those sources apart, so there were months during which all I had was a mess of disjointed files that didn't compile, and I wondered if I'd ever get it running at all.  So development from PCManFM-Mod to SpaceFM was not contiguous.

To create SpaceFM, I created a custom overlay for PCManFM's settings (if you compare the PCManFM settings file to SpaceFM's, you'll see it only stores a few dozen settings as opposed to thousands stored by SpaceFM - SpaceFM has an excellent memory).  I called this xsets, and you'll see its use peppered throughout SpaceFM's code.  This was basically a custom-fit way to extend PCManFM without a major rewrite (one person working on a mammoth project so it was a matter of finding a point of leverage).  It's essentially a big hack.  Even this hack wound up being hacked further because my original ideas for SpaceFM and xsets started to grow in unexpected directions once I had it running and I saw other possibilities.

Even PCMan did a major rewrite of the PCManFM 0.5.2 code (the 0.9 series), where he better separated the GUI from the filesystem functions (creating libfm).  However, he chose to employ gvfs and other gnome components.  He later regretted this somewhat as it created crashes and lots of bugfixing.  Same for udisks and udisks2: they're poorly developed and supported, they cause various system problems for users (which land in your lap), and they suck development time due to bugs and crashes.  They are HELL for FM devs.  Last I spoke to him, he was developing a fuse replacement kit for udisks, something along the lines of my udevil but API-based.

So when it comes to file manager dev, there are these candy-like toolkits like gvfs and udisks (and now systemd) that promise to solve all your problems.  But your development becomes tied to their huge stack of components, basically a DE dependency that can drag you anywhere, and your project's stability becomes subject to all their endless stability problems.  If you wonder why most FMs crash regularly, it's usually these deps.

SpaceFM has gone in the opposite direction, with its own glib-based VFS (it talks to the kernel directly for most file and memory functions), and it uses external CLI tools for mounting and other functions, giving users control and flexibility.  This also took me out of the maintenance loop on many issues, not to be underestimated!  So this codebase is very independent and has few dependencies to screw it up.  It doesn't even depend on gudev, let alone udisks.  It accesses udev's API directly.  You won't find many file managers that talk to udev directly.  udev itself changes rarely - I have never had to adjust anything API-related.

Users like this too (eg they can completely dump gvfs, udisks, consolekit, policykit, dbus, etc), but from a development perspective, that kind of independence from the likes of gvfs is pure gold.  It simply makes maintenance far less work so you can focus on your own creative work.  Otherwise most FM devs spend a lot of their time keeping up with the endless corporate changes pushed by Red Hat, et al.  Mostly these changes are functionally worthless and amount to busywork for downstream developers.  It's fundamentally why independent software doesn't genuinely evolve much in Linux: just to keep up, your team has to chase after Freedesktop's changing standards, API changes, etc.

So I think keeping independent is great for a FM.  Personally, I don't mind working on SpaceFM's code, because I know it well.  It has some room for growth, but one does need to tread carefully or it's easy to create breakage.  Plus it's like working on an old car or house: change one thing and you may discover more beneath it that needs attention.  This is what happened with alpha.  My changes were actually fairly shallow originally, using the original threading.  But this revealed problems in that original threading when it was pushed harder, so it had to be rewritten.  The new code is actually quite an improvement, leaner and faster, but by making such deep changes you begin at the start of a new maturity cycle.

So I think anyone planning extensive growth of SpaceFM would be wise to consider a rewrite of the basic structure, as you will find it hard to grow it much more.  Not impossible, but a rewrite might be more efficient.  Some of the code could certainly be reused.  It could use better separation between the GUI and file access code, perhaps even some asynchronous i/o in places to smooth out unresponsive filesystems.  (Because SpaceFM talks to the kernel more directly, it also tends to hang when the kernel isn't responsive.  Further, the GUI depends on a lot of filesystem context.  eg To show a menu, it has to look at the current directory, etc.  This makes the GUI laggy with laggy filesystems.  So more separation and some minor caches would be an improvement.)  This separation would also create the potential for movement away from GTK if that becomes desirable.

Add to all this that I'm not the world's best C programmer by a longshot.  I was a computer engineer and had written some drivers for my hardware in C a few decades ago, and had done some light crypto work in it, but I had never used C in application development (a far cry from writing a driver).  So it was a learning experience, and especially some of my early code reveals that.  Plus some days one is clearer-headed than other days.  :)  But it was a massive project with lots of chores to get done and tough problems to be solved, so I plowed through it best I could, not always gracefully.  Some parts could definitely use rewriting (a big job though, especially to get new code stable).

Overall, by bugfixing you'll get to know the code a bit and will have a better idea of what you might like to do differently.  You're also dealing with not just my code, but code from Thunar, gvfs, udisks and other places sewed in there, plus the added build support for GTK3.  So it's a mix of styles as well.  Yet it also contains some well-debugged and designed code; runs like a charm.

As for 'GUIs are evil', I've heard from quite a few people who say that SpaceFM is the first GUI file manager they could stand to use.  These are the midnight commander type folks.  ;)  That's not by accident - it aimed to be closer to the command line and scripting while still carrying some GUI perks.

**Comment by IgnorantGuru** [comment]
Actually I guess I could clarify that codebase issue: The underlying file manager code is very strong.  That's a tank, you can build whatever you like on it, and it has some remarkable freedom from dependencies at this point - you inherit a lot there.  The GUI is basically a circus.  If you're planning on extensive GUI innovation, I would rewrite it.  That's a big job, as it's not an ordinary UI, and there's a lot to it.  (eg in most applications you can't cut a bookmark, paste it into a random program menu, change it to a command that shows a custom dialog, etc.)  That part of the code has grown through several unpredictable phases and is much more experimental.  Even there, you could isolate certain areas if you didn't want to tackle it all.  For example, the file browser pane itself is a somewhat isolated object.  You'll just have to put up with chaos happening around you, but in a large project like this, that can be an effective way to work.

So I would say if you want to save yourself a lot of headaches from system issues, file manager growing pains, etc. and focus on GUI innovation, keep the core and rewrite/rework the UI, or parts thereof, as a general rule.  Just an opinion fwiw.

**Comment by BwackNinja** [comment]
I periodically take a look at this repo to see if things are still alive, and I'm glad someone is taking the reigns. I would have liked to contribute more, but I don't have as much free time as I used to.

It was a lot of fun while it lasted, though I would have liked to work on a rewrite myself. SpaceFM is a file manager, file opener, file archiver, and dialog box framework. There isn't anything I'd replace it with on any of my own systems.

This was a fun ride and I have to thank @IgnorantGuru for letting me be a part of it. Hopefully I'll get the chance to contribute again in the future.

**Comment by maximstewart** [comment]
Thank you for the work you have done! I love SpaceFM and use it on all of my systems. It is the best!

**Comment by sla0101** [comment]
Hello @IgnorantGuru I just saw a reply to an issue on Dec 2017...

I wasn't aware you are still active around here.

Are there any thoughts to pick SpaceFM back up again?

Teklad isn't very active, hasn't been any work in almost a year...

SpaceFM has so many bugs that need fixing, OH we need you please! 👍

**Comment by IgnorantGuru** [comment]
@sla0101

I'm not actively developing SpaceFM at this time, but I do keep half an eye on Github and will sometimes answer questions that might save someone research, etc.  It's not impossible I'll reawaken it for a bit of maintenance at some point.  Can't make any promises there, but it never hurts to report issues or provide pull requests.

Also should note that all the email addresses on my PGP key are currently defunct, so the best way to ping me is here on Github.  @OmegaPhil is also marginally available for anything major (eg if it becomes impossible to build, etc).

To minimize bug impacts, I recommend running the GTK2 build of SpaceFM with a lightweight theme, as GTK3 has probably gotten bugged up more.  I still use SpaceFM alpha regularly without any additional maintenance, but I realize some bugs have collected.  I regret not being able to do more with the long-term maintenance.

Subscribe to this repo for any project announcements down the line, and thanks for your continuing interest in SpaceFM.

**Comment by BwackNinja** [comment]
@sla0101 @IgnorantGuru 

I haven't quite disappeared either, though I've been a bit less active. I still use SpaceFM GTK3 without any real issues.

I'll take a look at the current bug list and see if there's anything I can help with.

**Comment by IgnorantGuru** [comment]
Hey @BwackNinja, thanks, always good to have you involved.  Good to hear GTK3 is still running well for you.  You can do any fixes as pull requests based on next and/or alpha, and I'll do my best to expedite those.

**Comment by orbea** [comment]
I just want to add that I use spacefm with a light gtk2 theme and most everything works without complaints. While there are some things that could be improved, I do not think it needs any major changes and I'll likely continue using spacefm as is for the foreseeable future. Additionally I did not really agree with some of the planned changes Teklad discussed on his issue tracker.

I appreciate that some people still remain to maintain this code base into the future. :)

**Comment by IgnorantGuru** [comment]
I recently read through all the newer issues, so all 150 currently open issues are now assigned to [milestones](https://github.com/IgnorantGuru/spacefm/milestones).  Here's how they break down by primary label:

[bug](https://github.com/IgnorantGuru/spacefm/issues?q=is%3Aopen+is%3Aissue+label%3Abug) (11) 7 in 1.0.6, with the rest in alpha or further from resolution
[unlabeled](https://github.com/IgnorantGuru/spacefm/issues?q=is%3Aopen+is%3Aissue+no%3Alabel) (23) 12 in 1.0.6, with most of the rest in far or limbo
[pending](https://github.com/IgnorantGuru/spacefm/issues?q=is%3Aopen+is%3Aissue+label%3Apending) (2) in alpha and waiting
[need info](https://github.com/IgnorantGuru/spacefm/issues?q=is%3Aopen+is%3Aissue+label%3A%22need+info%22) (12) in waiting or limbo
[request](https://github.com/IgnorantGuru/spacefm/issues?q=is%3Aopen+is%3Aissue+label%3Arequest) (102) 8 in 1.0.6, 9 in near

bug is applied to a reasonably confirmed bug.  7 of the 11 of those are due for fix by next release 1.0.6.  The remaining 4 concern unresolved instability in alpha, or a few that may take longer.

unlabeled are issues that are open for further review or correction, but may not be outright bugs, or may need further review by examining code before they can be closed or reclassified. 12 of those are due for correction or at least further review by 1.0.6, with the rest being longer range targets.

pending is applied to issues that have been addressed but have remaining work to do, so are not yet released.  This includes the main issue introducing the alpha branch, and one issue waiting for further action by others.

need info is applied when we need further feedback or research from a contributor or user, so these are generally in the waiting or limbo milestones, not likely to be resolved by me immediately.  Some of these may also be closed pending further research.

request is applied to feature requests or requests for functional changes, but not considered a bug or out of spec.  8 of these are due for inclusion or further review by next release, with another 9 in near, though that can change as they are further reviewed or researched, or as plans change.

Overall, there are 27 issues open in the [1.0.6 milestone](https://github.com/IgnorantGuru/spacefm/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.6), plus one pull request which will actually probably go in alpha.  Not all of those will be fixed or closed by that release, but something more is due to be done with them by then, such as examining code and reclassifying them.  Some of those have had fixes by Teklad, so his fixes may be applied.

There are also a few 'things to do' on my own list, which aren't on the public tracker but should be looked at by 1.0.6.

While some of the issues are likely fairly quick (a few hours), many of the open issues are labor-intensive, either requiring major recoding and testing, research, or extended troubleshooting.  There aren't a lot of quick 'bugfix day' type jobs remaining in SpaceFM (we went through years of that, so the current product is of a high standard in general).

I may arrange some time to review some of these at least, maybe working toward clearing some out gradually, and making a next release down the road.  There is also the problem of alpha, where some parts may need to be redesigned from scratch because neither I, nor anyone else who has tried, can reproduce/correct some issues, and backtraces haven't proved useful. (Inter-thread issues can be very difficult to track down.) But that's why it's called "alpha", and generally it's usable.

As for Teklad's fork, I honestly haven't kept up with his work - will take a look at some of the fixes - but I do know he merged in the current next as well as alpha branches, so any changes I make should be relatively trivial for him to import into that fork as well.  However, I probably won't be importing his work here in full for the time being, because he also made changes to the build system. This may represent an improvement, but I am unfamiliar, so it involves review, and such changes can also introduce instability across platforms, etc. I didn't design SpaceFM's entire build system, I just forked, fixed and extended it.  Nevertheless, due to the magic of git merges, it should be relatively easy for everyone to maintain their work on forks.

**Comment by sla0101** [comment]
@IgnorantGuru thanks for your reply...

@BwackNinja, you also help maintain SpaceFM?

Well this isn't saying much, but personally, the only issue I have with 1.0.4 and 1.0.5 is, sometimes clicking on a directory SpaceFM crashes and dissappears off the desktop. This was really problematice, more often in 1.0.5, so I reverted back to 1.0.4...

Thanks
