### ISSUE TITLE
Disable 'no subfolder' when here is no subfolder

### ISSUE THREAD

**Issue by mooooonbaby** [IgnorantGuru/spacefm#689]
Hi,

is it possible to disable that spacefm displays 'no subfolder' when there is no subfolder in  folder in tree view?

i can't find any point for that in the settings.

**Comment by IgnorantGuru** [comment]
No, there is no way to disable this.  It is a consequence of how the dir tree was originally designed.  I did look at it but not technically trivial to fix.  Not likely to change unless the current dir tree is replaced.
