### ISSUE TITLE
Using Underscore to sort files and folder like Windows Explorer?

### ISSUE THREAD

**Issue by mooooonbaby** [IgnorantGuru/spacefm#690]
I'm coming from the windows world and i use windows from time to time. in windows i used the underscore to sort some files and folder on top of the files/folder list. this doesn't work for the most file managers n linux. can this be changed so that spacefm doesn't ignore the underscore? i have a lot of files and folders sorted in this way and i don't want to rename all these files and folders.

**Comment by IgnorantGuru** [comment]
No this cannot be changed by the user, and the code generally uses libraries that determine the sort order (which is probably why Linux FMs behave similarly).

Changing SpaceFM's View|Panel n View|Sort|Natural and other sort settings may have some effect on order, but not in this case.
