### ISSUE TITLE
segfault in ptk/ptk-dir-tree.c

### ISSUE THREAD

**Issue by earlgrey-bis** [IgnorantGuru/spacefm#698]
Hello, I experience a bug :
~~~
Thread 1 "spacefm" received signal SIGSEGV, Segmentation fault.
ptk_dir_tree_iter_next (tree_model=0x7fffd0006e10, iter=0x7fffffffc890) at ptk/ptk-dir-tree.c:430
430	    if ( ! node->next )
~~~
After some basic surfing between GtkTreeView items and siblings.

( Debian stretch, spacefm:git release 1.0.5, arch:amd64, gtk+:2.24.31 )
- - -
A invalid **node** value ( not NULL, the value looks like somewhere in the stack ) may be related to your GtkTreeModel implementation.

**Comment by IgnorantGuru** [comment]
This is probably now fixed in next and alpha, or at least better prevented. Also if you were using an alpha build, this may have been due to some remaining timing issues between threads.  If the problem occurs again, please indicate output of spacefm --version.
