### ISSUE TITLE
Simple request - Add sftp as an accepted protocol handler along with ssh

### ISSUE THREAD

**Issue by techryda** [IgnorantGuru/spacefm#700]
Most times when I need to access an ssh server through spacefm, I, and I'm sure others, type `sftp://user@server/path` rather than the currently accepted (in spacefm): `ssh://user@server/path`

Can you please add sftp as a valid protocol handler?  I've already tested this by changing the protocol handler line from:
`ssh mtab_fs=fuse.sshfs`
to
`ssh sftp mtab_fs=fuse.sshfs`
and it works fine...

Thanks

**Comment by IgnorantGuru** [comment]
This has been added to defaults for next and alpha.  Note that if you have changed the ssh handler, you will need to press the Defaults button to see the new default Whitelist, or one may add sftp manually.  Thanks for the suggestion.

**Comment by techryda** [comment]
Thanks!
