### ISSUE TITLE
SpaceFM Loses All Configuration Data

### ISSUE THREAD

**Issue by antonio-malcolm** [IgnorantGuru/spacefm#706]
Logged in to my X session today, to find all my configuration data, plugin data, keyboard shortcuts, and custom menu actions are simply GONE. Also, it will not load my config backup. Great. Now I get to spend an hour reconfiguring everything. It completely dumped and overwrote everything under ~/.config/spacefm, and won't load configuration data from my backup.

This is version 1.0.5, GTK+ 3, on Void Linux, with LXDM and Openbox

**Comment by IgnorantGuru** [comment]
It is unprecedented for SpaceFM to lose its configuration, as in not a single report in all the years it has existed.  So I doubt it's SpaceFM's doing.

At any rate, there is no usable information in this report, and we've been having trouble with trolls creating false issues, so if you want some action taken, you'll need to provide reproducible steps.  "won't load configuration data from my backup" sounds highly unlikely and non-specific.  If you're just letting us know you had problems, noted.  Start it in a terminal and see if it produces any warnings or errors.  Check dir permissions.  The ~/.config/spacefm/ dir contains all of the configuration (as explained in detail in the Program Files section of the manual), so backing up that dir backs up the configuration.  They are plain text files and simply parsed, so not much to go wrong, unless you manually edited the files.  You can also export custom menu items for individual backups of those items.  Any scripts you created will be in that same config directory.

Closing this, but if you have further information, please feel free to post it and it will be reviewed.

**Comment by antonio-malcolm** [comment]
There's no manual editing of the backed up config files. It simply did not use them.
After restarting the daemon a few times, it finally appeared to pick them up.
Already noted the backups are in ~/.config/spacefm, and that's from where I create the backups.
Not sure I appreciate be hinted at as a "troll"; suffice it to say, not every issue you disagree with or see as a non-issue equates to trolling.

There's really not much explanation to be had, with regard to what happened to the configuration- the only app which creates and writes to that directory is SpaceFM. The only configs I touch are for compton, conky, openbox and dunst,, which require manual editing, though all directories and files have me as the owner group, which makes sense.

**Comment by IgnorantGuru** [comment]
Not equating you with a troll, just addressing the lack of usable detail in your report, and letting you know I can't tell the difference.  I'm glad that it's now magically working.

SpaceFM simply doesn't "completely dumped and overwrote everything under ~/.config/spacefm".  Not happening.  Show me in the code where that is done under any circumstance.  On the contrary, SpaceFM creates no less than three session files to fall back to in case of any problem, and it's configuration runs like a tank.  I should know, I restart it frequently under intense development conditions, switching back and forth between versions, testing code that crashes hard, etc.  Even I have never lost one single configuration setting.  So you're going to need some extraordinary proof to convince me there's a problem in SpaceFM.

None of what you're reporting makes any sense or is familiar in any way.  Perhaps something else on your system is affecting that directory. But it sounds like now it magically started, so obviously the session file is okay.  I'm glad you recovered your work.

**Comment by antonio-malcolm** [comment]
The session file is also from the backup. There's nothing 'magically' happening here. There's a reason for the configuration disappearing, and nothing else on my system writing to that directory. But, sardonic responses to the issue won't fix it, so it simply is what it is, I suppose.
