### ISSUE TITLE
1.0.6 Thumbnails Load Corrupt & Refresh Then Ok

### ISSUE THREAD

**Issue by 0pLuS0** [IgnorantGuru/spacefm#709]
Hello,

@IgnorantGuru thank you very much for bringing SpaceFM back into development, I really appreciate your work and efforts for SpaceFM!

I'm using deadbeef for my audio playing, and a plugin I use with it called infobar which displays a bio and lyrics of the artist, and can download an image and lyrics of the artists.

https://github.com/DeaDBeeF-Player/deadbeef
https://bitbucket.org/dsimbiriatin/deadbeef-infobar/wiki/Home

The infobar downloads the artist images to ~/.cache/deadbeef/bio and in 1.0.6 many times the thumbnail images are distorted, but view just fine in feh as example.

The images also appear in the ~/.thumbnails/normal distorted.

If I close ~/.cache/deadbeef/bio and then open it again, the images will now appear ok, and they also appear ok in the ~/.thumbnails/normal

In SpaceFM 1.0.5 the thumbnails appear just fine, I only have this problem with 1.0.6

Something odd I noticed, if I drag an image out of ~/.cache/deadbeef/bio to a $HOME directory, the thumbnail appears normal, then if I drag it back to ~/.cache/deadbeef/bio it appears distorted again, now that I don't understand. hmm

Please see the attached screen shot.

![spacefm](https://user-images.githubusercontent.com/36190223/38169043-42bd0fba-354e-11e8-80c1-aa8e124beb29.jpg)

```After making this post, I am no longer seeing this issue. I worked on this for 8 hours trying various things. For the first 4 hours, this would always happen, but then I installed several versions of SpaceFM, and wanted to know, do we need to keep the /tmp/spacefm.tmp path? Because I previously deleted it, but since leaving it, I am no longer seeing the problem, so I don't know if it's just coincidental.```

**Comment by IgnorantGuru** [comment]
Thanks for your report.  I doubt there were any changes in 1.0.6 code that would cause a thumbnail display issue.  This sounds more like a GTK library or other system-level malfunction.  SpaceFM uses GTK libraries for thumbnail resizing and display (or ffmpegthumbnailer for video thumbnails).  If it recurs, you might try reinstalling GTK or other components, try the default GTK theme to eliminate any theme-related issue, etc.  Also, most changes to 1.0.6 were tested for a fairly long time and no reports of issues on this.

/tmp/spacefm.tmp may be deleted at will, shouldn't cause any issue unless a custom command is running at the time, etc.  Certainly shouldn't cause any issue related to thumbnails.

Closing this as likely system-related, but please feel free to include any additional info and it can be reopened if needed.  You also might include the output of 'spacefm --version' if adding more details.

**Comment by 0pLuS0** [comment]
@IgnorantGuru thank you very much for your time.

Sorry I am not able to reproduce this, I really don't get why it all works so smooth now and for 4 hours straight it just wouldn't hmm

Anyhow just closing and reopening the directories seems to make everything smooth.

Thanks again, keep up the great work! SpaceFM is fantastic!

Cheers
