### ISSUE TITLE
1.0.6 Text file changes because of mime, any fix?

### ISSUE THREAD

**Issue by 0pLuS0** [IgnorantGuru/spacefm#710]
Hi,

mime seems to have some quirks, and because of it the icons in SpaceFM will change, when you don't have the .txt extension...

As a few examples, add the word ```From``` and any words after it, now becomes shown as a mailbox file in SpaceFM, the Properties will show you ```Type mailbox file application/mbox```

'file' on it, it will come back as;

~>file test
test: ASCII text

 ~>file -Lb --mime-type test
text/plain

Add ```BZh``` to a file and the icon changes and it now the icon looks like a compressed archive in SpaceFM.

~>file test 
test: bzip2 compressed data

~>file -Lb --mime-type test
application/x-bzip2

Putting an extension on a text file .txt will fix this, and I hope you will not be upset for me posting this, the problem is when using various applications, that just create text files and use them without an extension, if there's a way around this? So that these text files, the icons won't change, is there a way to create a mime setting in SpaceFM to deal with this?

Thank you

**Comment by IgnorantGuru** [comment]
Hi,

SpaceFM uses a different database (shared-mime-info) than 'file' for file type identification.  'file' is not strictly freedesktop compliant and will often give results which differ from your MIME configuration.

I recommend having a read through [MIME Menu](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#designmode-mime) which explains how SpaceFM handles MIME, and also explains [how to change/customize the identification of specific file types](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#designmode-mime-xml).

If you feel the default identification is wrong, that would be an issue to raise with the maintainers of [shared-mime-info](https://freedesktop.org/wiki/Specifications/shared-mime-info-spec/).

**Comment by 0pLuS0** [comment]
Thanks
