### ISSUE TITLE
[Design Mode] Edit NOT highlighted menu items

### ISSUE THREAD

**Issue by thierrybo** [IgnorantGuru/spacefm#717]
Hi,

I tried some contextual filters for a plugin. Unfortunately my last test do not let me activate the menu item anymore, it is always greyed out.

My question is: how do I edit this menu item now as SpaceFM allows only to do this on an highlighted item? It would be nice to be able to edit menu items whatever is their state.

Thierry B.

**Comment by IgnorantGuru** [comment]
Sure just right-click on any menu item, select Properties, and on the Context tab check option [Ignore Context](http://ignorantguru.github.io/spacefm/spacefm-manual-en.html#designmode-props-ignorecontext).  Then when you're done, turn that option back off.

**Comment by thierrybo** [comment]
ha, the more I use SpaceFM, the more i find it awesome! 

Thanks
