### ISSUE TITLE
Task manager not showing on Pop_OS

### ISSUE THREAD

**Issue by onjour** [IgnorantGuru/spacefm#745]
For some odd reason, my task manager don't show up anymore on SpaceFM 1.0.5 (see capture below).

I tried to reset my setup, uninstall and reinstall but nothing seems to get my task manager back. 

Pop-ups work well though (view -> task manager -> popups -> all tasks).

Any clue on this? Really enjoying SpaceFM for every other aspect.

![spacefm-no-task-manager](https://user-images.githubusercontent.com/39539070/53796004-7d533d80-3f33-11e9-8d84-34bce74bc869.png)

Thank you kindly.

**Comment by fbmoose48** [comment]
Did you even fix this? If so, how?
