### ISSUE TITLE
Can't acces shared folders via  SMB

### ISSUE THREAD

**Issue by Klairm** [IgnorantGuru/spacefm#766]
Every time I try to acces a smb folder or sftp, ie `smb://192.168.1.89`  or `sftp://192.168.1.89`

I get an error on console saying: 
`udevil: denied 73: fstype 'cifs' is not an allowed type`

Any tips?

EDIT: SFTP works, but SMB not

**Comment by ncmprhnsbl** [comment]
have a look at /etc/udevil/udevil.conf > "allowed_types =  "  section

**Comment by Klairm** [comment]
That solved it, thanks you
