### ISSUE TITLE
[Feature Request] "No Saved Tabs" Option to be configurable as default behaviour

### ISSUE THREAD

**Issue by ghost** [IgnorantGuru/spacefm#767]
I set spacefm as my default cinnamon file manager. Unfortunately every time I close spacefm window and open new one I get tabs with directories from old and new spacefm instance. This accumulates very fast which results in many opened tabs. This kind of visual clutter distracts me. I think it would be nice to have configuration option that makes spacefm not save/restore session on exit and lanuch.

I know I can create script that launches spacefm using -n option but that have many downsides:
1. I makes me use that script when I launch spacefm from command line
2. I need to configure cinnamon to use that script.
3. It adds additional layer in form of bash interpreter which makes launching spacefm slower -- I like my linux to be blazing fast. that's why I choose spacefm to be my file manager.

**Comment by cofi89** [comment]
Uncheck: File -> Save Tabs :)

**Comment by ghost** [comment]
It works.
