### ISSUE TITLE
Portage of spacefm to void linux

### ISSUE THREAD

**Issue by ghost** [IgnorantGuru/spacefm#792]
it would be helpful if you could consider adding the software to the void linux repo for the sake of convenience (and also for musl users)

**Comment by ncmprhnsbl** [comment]
but it has been for years: https://github.com/void-linux/void-packages/blob/a279abf769ef7cab6ebb49d8c99bf774a2ff97b8/srcpkgs/spacefm/template
and that is the place to request packages for void

**Comment by ghost** [comment]
@ncmprhnsbl weird, I looked it up multiple times yesterday on the void repo and it didn't show up
