### ISSUE TITLE
Thumbnails not rendering for *some* jpg/jpeg files

### ISSUE THREAD

**Issue by digidoor** [IgnorantGuru/spacefm#812]
Strange behavior where some .jpg thumbnails show up and others do not. Here is a screenshot of thunar above and spacefm below, where thunar shows thumbnails for all images and spacefm is only showing some:
![Screenshot_2023-02-27_14-36-44](https://user-images.githubusercontent.com/37601466/221701964-d17f07f9-9ace-4ec1-9725-9c7ba77d4283.png)
As to how this was arrived at, this is a fresh EndeavorOS install with XFCE desktop environment. Thunar is the default file manager and spacefm was added after from the AUR (via octopi). All thumbnails render correctly in dolphin as well; only spacefm is acting weird.

**Comment by ncmprhnsbl** [comment]
see:   View>Preferences>General  'Max Pic Size To Thumnail'  'kb value'
i'm guessing that the thumbnails that are not showing are larger than that 'kb value'
if so, to fix, increase that value.

**Comment by digidoor** [comment]
That was it! (It's View, not Edit, in case anyone else stumbles across this.)

**Comment by ncmprhnsbl** [comment]
oops :p,   fixed
